### ISSUE TITLE
Bing Search API subscriptions will expire on 3/31/2017

### ISSUE THREAD

**Issue by hannan-azam** [OrchardCMS/Orchard#7494] opened 2016-12-30 08:26 UTC
I was going through Bing Search API and came across this notice at the top of the page which says Bing Search API will expire on 3/31/2017 and new subscriptions can be made by using Azure.com

We are using this for Media Library Web Search Import. Will it impact us and do we need to make any changes for this?

Snapshot of the Bing Search API page is attached here:

![image](https://cloud.githubusercontent.com/assets/12548238/21561796/7e0a319c-ce93-11e6-834c-ba32902769d8.png)

**Comment by sebastienros** [comment] 2017-01-05 20:16
Duplicate of https://github.com/OrchardCMS/Orchard/issues/7118

**Closed by sebastienros** 2017-01-05 20:16 UTC
