### ISSUE TITLE
Bug with layout Ids updating a query by recipe

### ISSUE THREAD

**Issue by psp589** [OrchardCMS/Orchard#7017] opened 2016-07-01 10:40 UTC
I had problems updating a query by a recipe, the dynamic forms that were using the query (using a projection element) got lost the query, that's because when you update a query throw a recipe its layout Id is changed but the projection element is still referencing to the old id, so it can't find the query.
In order to fix this I've added a new string property called "Alias" to LayoutRecord which I fill with a guid.
Using this aproach I've fixed projectionParts and projectionElements, providing a migrations to fix existing elements.
I'll submit a pull request.

**Comment by sebastienros** [comment] 2016-08-18 19:48
@sfmskywalker can you confirm the issue and the resolution?

**Comment by sfmskywalker** [comment] 2016-09-24 18:04
I remember having fixed this already. Although the export includes the layout record id, it is not actually used during import (it's just an artifact of the Layouts module including everything in ElementData). Instead, it exports/imports the layout index. Importing happens during the `OnImportCompleted` phase, to ensure the `LayoutRecords` have been properly imported.

Anyway, I'll see if I can reproduce and if there's anything to fix.

**Comment by sfmskywalker** [comment] 2016-09-24 18:20
I can't reproduce the issue. This is what I tried:

1. Create a Query with 3 Query Layouts.
2. Create a Page with 3 Projection Elements. Each Projection Element has a different Query Layout selected.
3. Export both Query content items as well as Page content items.
4. Reset the site.
5. Import the exported recipe.
6. The exported Page site showed up with all Projection elements configured correctly.

I'm not saying that there is no issue, but whatever issue the OP experiences, it is not caused by what he describes, which means we should not use his PR.

@psp589 Can you please provide detailed repro steps on a vanilla Orchard 1.10.x installation? Thank you.

**Comment by humanoidcreature** [comment] 2016-10-09 14:03
I wanted to create an issue about a bug, but it seems this problem is similar to mine.

When you have a Query with Layouts settings (I tried the query with a Shape, and with an Html list, too) and you export it and import it back it breaks the query.
The problem is that when you import the query back, the records in Projection_LayoutRecord wich you want to import back are getting deleted and recreated, but with updated ID and in the Projections_ProjectionPartRecord the LayoutRecord_Id doesn't get updated.

Repro steps:
1. Create a Query with a Layouts settings
2. Export the Query
3. Import the Query

I tried it with a vanilla Orchard v.1.10.1.0.

**Comment by sfmskywalker** [comment] 2016-10-09 14:12
Do you see the same issue with the 1.10.x branch?

**Comment by humanoidcreature** [comment] 2016-10-09 14:25
It's fine on the 1.10.x branch.

**Comment by sfmskywalker** [comment] 2016-10-09 15:56
Alright, thanks for confirming. In that case we should close this issue. If someone is still able to reproduce the issue on the 1.10.x branch, we can reopen.

**Closed by sfmskywalker** 2016-10-09 15:56 UTC
