### ISSUE TITLE
1.9.3 - Multiple TaxonomyFields with Autocomplete enabled causes terms to be added to empty fields on save

### ISSUE THREAD

**Issue by j3ffb** [OrchardCMS/Orchard#6572] opened 2016-03-11 10:48 UTC
Repo:

1. Create a content type with 2 taxonomy fields (pointing to the same or different taxonomy's), both with autocomplete enabled.
2. Create a new item of this content type, entering terms in one of the fields and leaving the other one empty.
3. Edit the same item again and just publish.

Expected result: The item is saved with the same terms, one field should be empty.
Actual results: Both fields are populated with the same terms.

**Comment by j3ffb** [comment] 2016-03-11 11:03
Looked into this and I believe the issue is because when autocomplete is enabled it does not store all terms on the client, they are fetched via the service, for performance. On save all terms for all fields on the item are added to the model, 'TryUpdateModel' does not then set these to `checked = false` as the terms are not in the posted state.

I believe the fix is to have `GetAppliedTerms(part)` also pass the field, so that terms do not bleed across fields.

I will submit a pull request for the fix.

**Comment by BenedekFarkas** [comment] 2016-03-14 17:10
I followed the steps you described, but couldn't reproduce the issue.

**Comment by BenedekFarkas** [comment] 2016-03-14 19:34
Update: repro'd on 1.10, PR merged in.

**Closed by BenedekFarkas** 2016-03-14 19:34 UTC
