### ISSUE TITLE
Exception while cooking the default recipe from the command line

### ISSUE THREAD

**Issue by DanielStolt** [OrchardCMS/Orchard#6320] opened 2016-01-31 11:20 UTC
Reproduces on fresh clone of `1.10`. Steps:

1. Start `Orchard.exe`.
2. Execute command `setup /SiteName:"MySite" /DatabaseProvider:SqlCe /AdminUsername:admin /AdminPassword:password /Recipe:"Default"`
3. Check the log files (the exception will be emitted in all of them).

This reproduces both in `Debug` and `Release` configs, and both when running directly from source and when running from a published package.

Here's an excerpt where you can see the exception in context:

```
2016-01-31 12:12:21,387 [1] Orchard.Recipes.Services.RecipeExecutionLogger - (null) - INFO CommandStep: Executing command: layer create Authenticated /LayerRule:"authenticated" /Description:"The widgets in this layer are displayed when the user is authenticated"
2016-01-31 12:12:21,405 [1] Orchard.Recipes.Services.RecipeExecutionLogger - (null) - INFO CommandStep: Executing command: layer create Anonymous /LayerRule:"not authenticated" /Description:"The widgets in this layer are displayed when the user is anonymous"
2016-01-31 12:12:21,452 [1] Orchard.Recipes.Services.RecipeExecutionLogger - (null) - INFO CommandStep: Executing command: layer create Disabled /LayerRule:"false" /Description:"The widgets in this layer are never displayed"
2016-01-31 12:12:21,486 [1] Orchard.Recipes.Services.RecipeExecutionLogger - (null) - INFO CommandStep: Executing command: layer create TheHomepage /LayerRule:"url '~/'" /Description:"The widgets in this layer are displayed on the home page"
2016-01-31 12:12:21,505 [1] Orchard.Recipes.Services.RecipeExecutionLogger - (null) - INFO CommandStep: Executing command: site setting set baseurl
2016-01-31 12:12:21,521 [1] Orchard.Recipes.Services.RecipeExecutionLogger - (null) - INFO CommandStep: Executing command: menu create /MenuName:"Main Menu"
2016-01-31 12:12:21,552 [1] Orchard.Recipes.Services.RecipeExecutionLogger - (null) - INFO CommandStep: Executing command: page create /Slug:"welcome-to-orchard" /Title:"Welcome to Orchard!" /Path:"welcome-to-orchard" /Homepage:true /Publish:true /UseWelcomeText:true
2016-01-31 12:12:22,570 [1] Orchard.Exceptions.DefaultExceptionPolicy - (null) - ERROR An unexpected exception was caught
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at System.Web.HttpRequest..ctor(String filename, String url, String queryString)
   at Orchard.Mvc.MvcModule.HttpContextPlaceholder.get_Request()
   at Orchard.Tokens.Providers.RequestTokens.Evaluate(EvaluateContext context)
   at Orchard.Events.DelegateHelper.<>c__DisplayClass14_0`2.<BuildAction>b__0(Object target, Object[] p)
   at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue)
   at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue)
2016-01-31 12:12:22,708 [1] Orchard.Recipes.Services.RecipeExecutionLogger - (null) - INFO CommandStep: Executing command: menuitem create /MenuPosition:"0" /MenuText:"Home" /Url:"~/" /MenuName:"Main Menu"
2016-01-31 12:12:22,771 [1] Orchard.Recipes.Services.RecipeExecutionLogger - (null) - INFO CommandStep: Executing command: widget create MenuWidget /Title:"Main Menu" /RenderTitle:false /Zone:"Navigation" /Position:"1" /Layer:"Default" /Identity:"MenuWidget1" /MenuName:"Main Menu"
2016-01-31 12:12:22,840 [1] Orchard.Recipes.Services.RecipeExecutionLogger - (null) - INFO CommandStep: Executing command: theme activate "The Theme Machine"
2016-01-31 12:12:22,855 [1] Orchard.Recipes.Providers.RecipeHandlers.RecipeExecutionStepHandler - (null) - INFO Finished executing recipe step 'Command'.
```

**Comment by sfmskywalker** [comment] 2016-01-31 12:59
The issue is that the `HttpContextPlaceHolder` is constructed with a `baseUrl` delegate that looks like this:

```C#
var baseUrl = new Func<string>(() => siteService.GetSiteSettings().BaseUrl);
```

When Setup executes from the command line (Orchard.exe), there will have been no BaseUrl set.
This can be fixed by returning a default value in case BaseUrl is null:

```C#
var baseUrl = new Func<string>(() => siteService.GetSiteSettings().BaseUrl ?? "http://localhost" /* When Setup is running from the command line, no BaseUrl exists yet. */);
```

The actual default value doesn't really matter, just as long as it is a valid URI.

**Closed** 2016-01-31 13:26 UTC

**Comment by jtkech** [comment] 2016-02-01 01:33
@sfmskywalker 

Just for infos because that's what i've first proposed (without thinking of this use case) before the first review of my PR. This to prevent from an exception when base url is not set. And, if not set, I also needed to add the `HostingEnvironment.ApplicationVirtualPath` (if a virtual directory is used as OrchardLocal). See here line 43:

https://github.com/jtkech/Orchard/blob/fbd0f878f5c058ff35caa37d5ebfe54d1b72e484/src/Orchard/Mvc/MvcModule.cs

Here the part of code i was using (i was also using the tenant prefix):

            var baseUrl = new Func<string>(() => {
                var url = siteService.GetSiteSettings().BaseUrl;
                return !string.IsNullOrWhiteSpace(url) ? !string.IsNullOrWhiteSpace(prefix) ?
                    url.TrimEnd('/') + "/" + prefix : url : "http://localhost"
                    + System.Web.Hosting.HostingEnvironment.ApplicationVirtualPath;
            });

I don't remember if i've tested this version through the command line, maybe we have to check `HostingEnvironment.IsHosted?`, i don't remember.

Best

**Comment by sfmskywalker** [comment] 2016-02-01 22:21
I see, your version takes into account more specifics to create the base URL when not configured. I'll try it and see how it behaves in both a normal HTTP context as well as Orchard.exe. Thanks. :)

**Comment by sfmskywalker** [comment] 2016-02-01 22:30
After a brief discussion with @sebastienros , he suggests that the *BaseUrl* should be provided by the *setup* command, which could have a default value of `"http://localhost:3020/OrchardLocal"`. From the web context, this would not be necessary since the base URL would be taken from the current request.

**Comment by jtkech** [comment] 2016-02-01 23:19
@sfmskywalker, @sebastienros 

Ok, maybe i needed to use `ApplicationVirtualPath` only if the baseUrl was not set and through the web context. If so, through the command line, maybe `"http://localhost"` is enough? To be tested.

Best

**Comment by DanielStolt** [comment] 2016-02-02 12:31
I think that it would be more robust for the base URL in command-line execution to be set by the command-line host rather than by the setup command specifically, because then it would cover all other commands as well where this might happen.

**Comment by sfmskywalker** [comment] 2016-02-02 13:11
Good point, and this is probably what Sébastien ment in the first place.

**Comment by jtkech** [comment] 2016-02-03 22:59
@sfmskywalker,  @DanielStolt, @sebastienros 

After re-thinking about this, i've the feeling that the best solution is what @sfmskywalker first proposed by providing in `MvcModule` a default `baseUrl` if not set. This because it could solve the issue at the source, and could solve other issues when you clear the `baseUrl` through the dashboard settings.

Just re-tried it with the part of code i've proposed in a previous comment (but without the tenant prefix). In a web context or through the command line, it seems that the domain name doesn't matter, it works with `http://localhost` or e.g `http://foo`.

In a web context, i needed to add `ApplicationVirtualPath` when no `baseUrl` and using a `virtual directory` (as OrchardLocal or another name). Through the command line, `HostingEnvironment.ApplicationVirtualPath` returns to me `'/'`, so i've added a `.TrimEnd('/')`.

So, i propose this:

    using System.Web.Hosting;
    ...
            var baseUrl = new Func<string>(() => {
                var url = siteService.GetSiteSettings().BaseUrl;
                return !string.IsNullOrWhiteSpace(url) ? url : "http://localhost"
                    + HostingEnvironment.ApplicationVirtualPath.TrimEnd('/');

Depending on your choice, let me know if i have to do a PR. If so, i think in the dev branch because all other updates around this have been done only in dev.

Best

**Comment by DanielStolt** [comment] 2016-02-09 01:00
This solution sort of makes sense too - I'm not against it.
