### ISSUE TITLE
In Orchard 1.10.2 generated content, will not be displayed

### ISSUE THREAD

**Issue by asemandeveloper** [OrchardCMS/Orchard#7663] opened 2017-04-14 13:41 UTC
In Pre-release of Orchard 1.10.2 sometimes generated content, will not be displayed in "Manage Content List"

**Comment by sebastienros** [comment] 2017-04-14 17:21
Can you provide a repro or more details, what do you mean by "generated content"?

**Comment by asemandeveloper** [comment] 2017-04-15 03:57
Steps are as follows
1: In Settings add ar-SA Culture
2: Select ar-SA as Default Site Culture
3: click Clone in Manage Content for  Welcome to Orchard Page
4: Exit of Orchard CMS
5: Re-run Orchard CMS
6: In Manage Content i see an item in the list, and no two items

**Comment by sebastienros** [comment] 2017-04-20 19:14
Did you notice the Culture drop down list on this screen that lets you filter the content items?

@MatteoPiovanelli-Laser can you confirm this is the expected behavior?

**Comment by MatteoPiovanelli-Laser** [comment] 2017-04-21 07:58
Hi.

I am unable to reproduce this. I followed the steps @asemandeveloper wrote, but I see stuff correctly in the content list.

> 4: Exit of Orchard CMS

I am not 100% sure what you mean there. I tries closing the browser, as well as restarting iis. In both cases I still saw no issues in the content list.

I have attempted this with the current 1.10.2.

**Closed** 2017-04-25 15:53 UTC
