### ISSUE TITLE
Using lib for assembly references rather than NuGet

### ISSUE THREAD

**Issue by gcsuk** [OrchardCMS/Orchard#6148] opened 2015-12-08 16:43 UTC
Because Orchard uses the lib folder, rather than NuGet, bringing in packages that have dependencies such as MVC rewrites all of the project references. In order to make Orchard "update-able" we need to manually undo all of these references every time we use NuGet.

For a solution the size of ours, with over 120 projects, this is a large task and it has to be repeated across the team almost daily as we update NuGet packages from our micro services.

The lib folder was a great idea when the Orchard project was started, but NuGet is now a more appealing alternative.

**Comment by IntranetFactory** [comment] 2015-12-08 16:55
I don't like the idea of being forced to use NuGet - I strongly prefer to have the matching version of all required dependencies directly in the repo.

**Comment by gcsuk** [comment] 2015-12-08 17:01
The versions are still set, they are just set in packages.config. You never need to change the versions after restoring initial packages.

**Comment by PaulDevenney** [comment] 2015-12-08 17:06
@IntranetFactory There is no requirement to ever update the versions past those that would be defined in the Orchard solution (so this would essentially be the same as today, but also provide a standard way to ensure updates occur). Those that don't want to play around with the values can just build the project, let nuget download the dependencies, then check the whole lot into their own repo (or just download binaries). For those that are trying to integrate external packages that depend on nuget references higher than the (sometimes non-standard) versions in Orchard, this will be a godsend.

**Comment by IntranetFactory** [comment] 2015-12-08 17:07
We can't use a tool like NuGet which can add additional files to our product projects. All dependencies need always to approved if they have an acceptable license. 

We see NuGet as a trouble maker - frequently causing issues with older versions of dependencies being gone or causing conflicts. 

And we always need to have all dependencies of a build in the repo. Disc space is cheap, so I see no reason why I should hope the NuGet and the internet connection is available when a building a certain version or branch.

**Comment by PaulDevenney** [comment] 2015-12-08 17:10
The dependency is no different if it is in a lib folder or was pulled down from nuget. The piece of software would have the same license (NHiberate x.x is the same whether it is already in a lib folder, or downloads on first build)

As I mentioned above, you can take the decision to commit the packages folder to your repo, rather than exclude it.

**Comment by IntranetFactory** [comment] 2015-12-08 17:14
Afaik NuGet is not protecting you if a license for a package changes e.g. from BSD to GPL. So you can run into big legal troubles without even noticing. Same if a license in a single file in such a package changes. Due to the viral nature if the GPL all your software might be silently GPLed.

**Comment by sebastienros** [comment] 2015-12-08 17:22
@IntranetFactory Independently of whether I am with or against using Nuget, I think the legal issue doesn't exist, your legal team will approve a specific package version, and you just don't upgrade. I have had the same issue with an internal product in Microsoft, where only Json.NET version 6.0.1 could be used as the newer version had not been validated yet. And if Orchard decides to upgrade something depending on JSon.NET 6.0.2 then you would have the same issue with libs.

I have seen many teams using Orchard trying to move it to Nuget not to be open to the change. I unfortunately don't remember all the arguments against it (in Orchard) but one matter was that we were using custom builds. Keeping them in the lib folder is one solution, creating our own packages on Nuget is another.

**Comment by sebastienros** [comment] 2015-12-08 17:25
I have a question about the build/deploy pipeline. How does it impact what we have today:
- `build.cmd`
- `build Precompiled`
- Visual Studio publish (webdeploy)
- Building the __web__ package on release
- Azure Cloud Services deployment

We need to assess what is broken and not.

**Comment by IntranetFactory** [comment] 2015-12-08 17:37
> And if Orchard decides to upgrade something depending on JSon.NET 6.0.2 then you would have the same issue with libs.

But how should this be detected? Currently it's easy - just compare lib folder, even if just a license header in a file was changed it will be easily discovered. It could even be easier if the lib folder would be in a dedicated repo - then just checking the history of that repo would be sufficient.

In the future then checking each project folder for dependency changes?

**Comment by bleroy** [comment] 2015-12-08 17:46
The CREDITS.txt file should be kept up-to-date, and such changes should be called out in release notes. We need to be vigilant about license changes no matter what.

**Comment by IntranetFactory** [comment] 2015-12-08 17:55
I doubt that CREDITS.txt is up-to-date now e.g. it seems that I can't find Angular mentioned in it. So if the dependencies become invisible in the repo after the lib folder is removed I doubt that new dependencies or changed dependencies can be detected easier.

**Comment by gcsuk** [comment] 2015-12-08 18:05
In that respect, the packages folder replaces lib so it is just as visible

**Comment by IntranetFactory** [comment] 2015-12-08 18:13
> In that respect, the packages folder replaces lib so it is just as visible
No.

The folder names in packages contain a version number - so you can't compare two version of that folders to detect changed licenses. You are forced to review folder by folder !

Again: can't such a breaking change be postponed for v2 ?

**Comment by gcsuk** [comment] 2015-12-08 18:28
It'd happening in v2 anyway, but there are no breaking changes in this PR as I kept all versions the same. Since we have to cross the bridge with v2 we may as well reap the benefits now - especially as I have done all the work for the PR so the hard bit is done.

**Comment by IntranetFactory** [comment] 2015-12-08 18:31
I understand that it's not breaking for you - but it's breaking our processes, without any gain.

**Comment by DanielStolt** [comment] 2015-12-09 01:03
@IntranetFactory As @sebastienros suggested above, you might add the `packages` folder to your source control. If you do that, given that @gcsuk added the nuget references using specific version numbers, wouldn't the process be exactly the same for you as before? Technically, it's like the `lib` folder was simply moved to `src\packages`, isn't it?

**Comment by IntranetFactory** [comment] 2015-12-09 01:56
Currently we can just compare the old and the new version of the lib folder to see changed dependencies (at least for .dll dependencies) especially for changed license files and headers. With the packages folder a compare is not possible as the dependencies exist in folders with version numbers.

**Comment by kappas** [comment] 2015-12-09 04:09
We have had so many issues with Orchard's Lib folder and our own custom modules using nuget, that it will be really big improvement to have nuget support for Orchard too.

And I really hate to put external libs to Git as it get bloated. Cloning takes too much time..

For getting that licensing information of used nuget packages as conveniently as possible, it could be possible automated in some sense. Just checked if any other was having same issues and run into this http://haacked.com/archive/2015/03/28/download-nuget-package-licenses/

Combine that into your pipeline and save the output into Git. Then you can compare changes in licensing information after nuget updates...

**Comment by PaulDevenney** [comment] 2015-12-09 09:34
You could easily write something to scan all `packages.config` files for changes. Assuming you use source control, you would see after a getting a new version of Orchard if any of them had changed. If one has, you should verify if the licensing has been updated. If it hasn't...the files in that folder won't have changed, so there is nothing to even look at. A PR from an upgrade branch will show if any dll has changed (if you do what I mentioned above and check in packages into source control). I really can't see any difference between these two techniques from the point of what comes as part of the Orchard Product. One comes with specific versions of the files in the `lib` folder, the other comes with specific versions of the files in the `packages` folder. The primary difference is that people could _choose_ to update them using the most common mechanism for .NET projects and avoid large numbers of painful conflicts.

@sebastienros point is pretty important though. Checking out the provided build/deploy commands is needed.

**Comment by IntranetFactory** [comment] 2015-12-09 10:47
@kappas Thank you. That seems to be a great solution, which would even be easier then the one we have in use today.

**Comment by gcsuk** [comment] 2015-12-09 11:55
So now we all want NuGet :)
Just need to check the point made by @sebastienros

**Comment by dcinzona** [comment] 2015-12-09 13:10
You can absolutely use Nuget in your own custom modules. We are using the Nuget packages for IdentityServer3 as well as EntityFramework and our own custom internal PCL.
Conversely, if you wanted to, you could manually update the DLLs in the Lib folder to the newer versions, just don't forget to update Orchard.Web/web.config to match.

**Comment by gcsuk** [comment] 2015-12-09 13:20
Yes we use NuGet throughout our solution, the problem is some of our micro services (most) have dependencies such as AutoFac, WebApi etc, so when updating packages NuGet re-points all of our projects to use packages folder rather than lib. Then we have to manually discard all the changes, which takes ages and has to be repeated often. Having everything in the single packages folder will sort this out as NuGet will leave the references alone and it will all be consistent.

No more references to 2 different folders full of dependencies, just the single Packages folder.

We don't touch the core orchard folders (like lib) as we have set up our solution to be able to bring in the latest Orchard from GitHub whenever we want, so that would revert the library updates :/

**Comment by dcinzona** [comment] 2015-12-09 13:52
@gcsuk  Are your micro-services running as Orchard modules?  That's odd that updating the nuget package re-points all projects to use the packages folder rather than the lib folder.  We don't have that issue for any projects that don't have the nuget package installed (i.e. all core).  We can update nuget packages fine without any projects that don't have that nuget package installed being modified.  

* Are the versions that your micro-services require different than those Orchard uses?  
  * If not, why not point your modules to the lib folder instead of using Nuget at all?
  * If so, you're going to run into some problems trying to keep the two in sync.  You can potentially have two different versions of libraries (one in the Bin and one in Dependencies), however, the web.config needs to match the highest version available.  I'm not sure as to the hierarchy of which version is used (if the same file exists in the dependencies folder as well as the bin folder, does it load the file in dependencies over the file in bin?

If Orchard switches everything to Nuget packages instead of Lib, there's going to be the issue of hard set versions in the Nuget packages. If you try to install a new Nuget package with a dependency that is higher than that which is set in Packages.config, the install will fail.  You would then have to decide if you really need that version, and if so, have to update all the Packages.config files in all modules (which will be an nightmare come time to update Orchard).

One option for Orchard would be to constantly be iterating on lib versions as much as possible, with the focus of updating to the newest when available.  This poses a couple of different problems, however:
 1.  Trying to install a Nuget package that has a max version dependency which is older than the version installed in Orchard (package install will fail)
 2.  Actually updating and testing to make sure that the new library doesn't break anything in Core.
 3.  Custom modules have to be tested to make sure they also don't break with the new library.

Regarding custom modules and updating: perhaps a "Max Orchard Version" setting could be defined in the module, and when not defined, defaults to latest version.  Then, updating a website that was deployed from a released version (i.e. from the Azure Marketplace) could also be a potential issue because modules might end up being disabled if they don't match the latest version.  An Orchard Upgrade Service would be a welcomed feature in this scenario because it could potentially check all activated and installed modules prior to updating and warn the user in the case that a module won't work with the latest version.

In my perfect world, modules use the libraries stored in their specific Bin directory, rather than the website root.  This way, modules can be independent of the base libraries.  In this scenario, Orchard would have to make sure that each dependency is loading it's own libraries so that core modules use whatever DLL version is required for them.  I actually don't think this is possible, as each module would potentially have to run as it's own virtual application, with link references to any dependencies, including Orchard.core.  This could also exponentially increase the memory requirements for the web app and have significant performance costs.

**Comment by sebastienros** [comment] 2015-12-10 20:25
TODO:
- [ ] Finish the migration of the other packages, by adding them to Nuget
- [ ] Test the deployment strategies

**Comment by gcsuk** [comment] 2015-12-11 09:03
@sebastienros Is there a specific account to use on NuGet? I have my own so can use that if no objections, or we could create one specifically for Orchard (if there isn't one already).

**Comment by sebastienros** [comment] 2015-12-11 16:55
@gcsuk I meant create the needed Nuget packages, and add us as owners on the Nuget package, not your branch.

**Comment by gcsuk** [comment] 2015-12-14 09:03
No problem @sebastienros. I wasn't sure which you meant, so I did both.

**Comment by Piedone** [comment] 2015-12-22 21:50
@gcsuk have you tested deployment as Sebastien described above?

**Comment by Piedone** [comment] 2015-12-26 14:11
Also another issue @gcsuk : what about updates? Currently if a library in Orchard changes you, as a third-party module developer will just get the update if your module references it, no need to change anything if the library doesn't contain breaking changes (since the reference stays the same).

With NuGet packages however the DLL paths will change with version updates (since the package folders' names contain the version number) so every library update used by your module is a lightly breaking change (since you'll need to change the reference in the csproj). Note that unlike when you update a package in your own solution these references won't be updated for you by NuGet package update since the update happens in the Orchard repo, independent from your app.

**Comment by sebastienros** [comment] 2016-01-05 20:35
FYI we talked about it during 1/5/16 meeting, it should work. Zoltan will try to repro the issue.

**Comment by Piedone** [comment] 2016-01-06 00:52
I tested it now:

1. Cloned the fork and added a module as an example of a third-party module.
2. Added v7.0.1 of Json.NET to the module, which is the version used by Orchard (which would also happen if this would be the latest version of Json.NET). This properly added the package and the library reference to the csproj as below.
3. Let's suppose Json.NET get upgraded in Orchard to the latest 8.0.1 version. So I updated the package, but in a branch separate from where my module was created, simulating that this happens in the Orchard repo where my module is not present. During the upgrade NuGet prompted me whether I also want to update the package in all projects that use it, which I've chosen. This, as expected, updated all the csproj and packages.config files to use the new library.
4. I merged in the Json.NET updated into the branch with my module, which is similar to what would happen if I'd update/upgrade Orchard itself. So at this point all the built-in Orchard modules and other projects where using the 8.0.1 package and referencing this assembly under packages\Newtonsoft.Json.8.0.1\lib\net45\Newtonsoft.Json.dll while my module was referencing the 7.0.1 version of the package and the assembly under packages\Newtonsoft.Json.7.0.1\lib\net45\Newtonsoft.Json.dll.
5. Now I wanted my module to use the upgraded version also utilized by Orchard. Due to assembly redirects my module's code at this point was actually also executing the latest version of the assembly but when writing code I was still seeing the old version of course since that one was referenced by the module. Thus I had to manually update the package in my module too to the latest version. **Note that this is the inconvenience I was talking about.** If the version used by Orchard happened to be not the latest version then this step would have been a bit more complicated as then one needs to also specify the version number. 

The above illustrates my point: every package update in Orchard will require module and theme authors to update all the packages for all their extension to the exact new version Orchard is using. That is of course if they a) want to actually make use of the latest packages in their code and b) don't have multiple versions of the packages being restored and stored in the packages folder.

This is what I classified as "lightly breaking" above: you're not absolutely forced to do this as an extension author but you can't avoid it if you want to keep your extensions clean (and you have to do it to use newly added pieces of interface in the updated library since that won't be possible without updating the reference).

Now compare this to the relevant workflow of today: nothing to do. If your extension references e.g. lib\newtonsoft.json\Newtonsoft.Json.dll then the new library will be under the same path and you'll be able to use it from your extension right away.

Since third-party extensions are not part of the Orchard solution authors will need to do such updated themselves, which will be extremely tedious with many extensions to maintain unless it can be automated to a high degree. E.g. can we just magically synchronize all projects in a solution to use the versions that Orchard uses? @dcinzona I think you mentioned something for this during the meeting?

Reference added to the test module's csproj when adding the NuGet package:
```
    <Reference Include="Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <HintPath>..\..\..\packages\Newtonsoft.Json.7.0.1\lib\net45\Newtonsoft.Json.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

**Comment by gcsuk** [comment] 2016-01-07 10:15
@sebastienros @sfmskywalker I have successfully published to Azure and the file system.

I am just checking Precompiled, as it is throwing an error with Orchard.Layouts - I am going to determine if this happens in Dev as I cannot see how my changes would cause this.

Site published to Azure: http://gcsukorchard.azurewebsites.net/

**Comment by gcsuk** [comment] 2016-01-07 16:47
@Piedone If you wanted your modules to use the same as Orchard, then by having them in Nuget the "Manage packages for solution" option (rather than at project level) will show at-a-glance every package in your solution, now including Orchard modules, and the "Consolidate" tab (in 2015 and even better in Update 1) will let you update your custom modules at the click of a button to the new Orchard version.

Breaking changes would be the same in this scenario as would updating lib, as the same DLL is ultimately referenced.

It is actually better than at the moment with lib, in scenarios where csproj files are referencing version 1.X and the lib folder was actually updated to version 2.X without any project reference updates (there were a lot of these as I went through all the csproj files). Granted that won't break it, but it is certainly untidy and inconsistent.

**Comment by sebastienros** [comment] 2016-01-07 20:52
I read your comment @Piedone thanks. I think the issue you showed is totally fine and expected. It's only at dev time, and any breaking upgrade would have broken with both solutions. So let's break everything and see how the world reacts.

**Closed** 2016-01-07 20:53 UTC

**Comment by Piedone** [comment] 2016-01-07 22:39
Well it's not just dev time: you have to fix it at dev time sure, but another tricky part is that if there actually happens to be a breaking (i.e. a different interface) change in a library then you'll notice this only at runtime, not at compile time: if you don't care about explicitly updating your package references to the Orchard version then your code will be built with the old library but due to the assembly redirects the new one will be used: this will yield you a runtime error.

So all in all with this you as a module developer need to always update your module's packages to the version used by Orchard.

**Comment by sebastienros** [comment] 2016-01-08 00:24
Quoting you 

> if there actually happens to be a breaking (i.e. a different interface) change in a library then you'll notice this only at runtime

Then quoting myself

> any breaking upgrade would have broken with both solutions

**Comment by sebastienros** [comment] 2016-01-08 00:26
> So all in all with this you as a module developer need to always update your module's packages to the version used by Orchard.

I don't agree. You don't __always need__. Like without nuget there are scenarios where nothing has to be done, if the the library doesn't have breaking changes.

**Comment by Piedone** [comment] 2016-01-08 00:44
There is a difference: with the lib folder a breaking change will break immediately the next time you try to build the solution (since the project references the now updated library, because it's under the same path). In the NuGet case a build error will only happen if you update the package for your module. If you don't update then it will cause a runtime error.

This is crucial: a breaking change will break your code of course any way but it does matter whether it will break in a very obvious way or in an unfortunate case you'll only see it happening from the logs in production.

Hence I say that this means that practically you'll always need to keep your modules' packages in sync with the Orchard version because otherwise you simply won't notice breaking changes early enough.

And again, compared to what you need to do today to find out that you have a breaking change: nothing, just build.

Do you see my point?

That being said this is obviously a downside that we need to work around. The issue is that this is not something that you can just people expect to know because seemingly everything will work and then subtle issues will arise... The minimum would be to document this @gcsuk please, together with the recommended solution you mentioned above.

**Comment by sebastienros** [comment] 2016-01-08 00:50
I see your point. Didn't someone say that in this case Nuget would update all the references of the solution automatically? Then showing the error without having to do update anything manually?

**Comment by dcinzona** [comment] 2016-01-08 01:39
@sebastienros yes, you can update all nuget references for all projects in a solution by using either package manager console or right clicking on the solution itself, and selecting the option to manage nuget packages.  There you can update each project individually, or all together for each package.

**Comment by dcinzona** [comment] 2016-01-08 01:43
Personally, I'm a huge fan of the consolidate feature in VS 2015. 
Also, using Nuget packages lets you quickly see at a glance which projects are referencing which versions.
![capture](https://cloud.githubusercontent.com/assets/52411/12188026/5ff69c82-b57f-11e5-8e1c-ae6a54fdeb83.PNG)
