### ISSUE TITLE
Layout elements don't evaluate tokens

### ISSUE THREAD

**Issue by bleroy** [OrchardCMS/Orchard#5407] opened 2015-06-21 21:15 UTC
Most fields in element editors are tokenized, but the tokens are actually not evaluated. For example, add a paragraph element, and use "The title is: #{Content.DisplayText}" as its contents. The token should get evaluated, but isn't.

**Comment by sebastienros** [comment] 2015-06-22 22:34
Duplicate of #5400 ?

**Comment by sfmskywalker** [comment] 2015-06-24 10:11
Maybe not a duplicate, but a related issue. This issue is about evaluating tokens in Paragraph and Html elements, while issue #5400 mentions tokens not being evaluated for the Label property of the `TextField` element. Maybe we should combine the two tickets where each element that needs to have token evaluation implemented is listed. I'll go over each element in `Layouts` as well as `Dynamic Forms` and make sure that the labels as well as contents are properly evaluated.

**Comment by sfmskywalker** [comment] 2015-06-27 17:59
To fix this ,we have at least two options:
1) Invoke the `ITokenizer` to process the text.
2) Invoke the `IHtmlFilter` instances and rely on the `TokenHtmlFilter` to be enabled (associated with the `Orchard.Tokens.HtmlFilter` feature in the `Orchard.Tokens` module.

The problem with the first option is that we don't take advantage of the IHtmlFilter implementations, limiting custom processing of elements' content.

The problem with the second approach is that we don't have a way to pass along context to the html filters. In the case of the `TokenHtmlFilter` we need to pass along the Content item for example to serve as context to the tokenizer.

One suggestion to solve this would be to break the `IHtmlFilter` signature by adding a third argument called `context`. This would be an `IDictionary<string, object>`. It is up to the various implementations to deal with the values. In the case of the `TokenHtmlFilter` implementation, it would simply feed this dictionary into the tokenizer.

Other suggestions are mere workarounds, such as having the `TokenHtmlFilter` implement some additional interface that the various layout element drivers are aware of and see if they can cast to that interface. If so, they would either set some context or invoke an alternative processing method.

Another work around would be to just do the tokenization and not use html filters at all.

Personally I'd break the interface and implementations, but then we'd have to retarget this ticket to 1.10. So perhaps for now I'll do one of the workarounds.

Thoughts?

**Comment by sfmskywalker** [comment] 2015-06-29 11:03
Fixed in 5b40567b6dae9b3c69e25dc7acf0508dc2285aaa.

**Closed by sfmskywalker** 2015-06-29 11:03 UTC
Labels: enhancement, Layouts
