### ISSUE TITLE
AntiForgeryToken Workflow 

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#8051] opened 2018-05-11 09:10 UTC
on dev 1.1x when creating a workflow it works all fine . but when editing an existing workflow .
and exception is thrown AntiForgeryToken does not exist .

**Comment by sfmskywalker** [comment] 2018-05-11 15:17
I tried both **dev** and **1.10.x**, but could not reproduce the issue you mentioned. I'm closing this one, but feel free to reopen if you have repro steps on a vanilla Orchard installation.

**Closed as completed by sfmskywalker** 2018-05-11 15:17 UTC
