### ISSUE TITLE
Orchard Content BodyPart rich text contains "<" will cause XmlException

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/Orchard#8174] opened 2019-03-23 05:59 UTC
Hi,

I direct copy full content of an HTML page, then paste and save into a content with BodyPart.

Then cuase the XMLException , the "Content Items" page could not display anymore.

I think it's because the source page contain a un-escaped text "<".

### The source text 
![The text](https://user-images.githubusercontent.com/3222379/54862277-35297d00-4d73-11e9-8c9a-e36f372414bd.png)

### Code error
![Code Error](https://user-images.githubusercontent.com/3222379/54862276-3064c900-4d73-11e9-98fe-99783b01b3c0.png)

### Error encoded text in debugger
![image](https://user-images.githubusercontent.com/3222379/54862290-6144fe00-4d73-11e9-8d18-f93416a0eee5.png)

### Error message
`Oops. Something went wrong ... sorry
An unhandled exception has occurred and the request was terminated. Please refresh the page. If the error persists, go back

could not set a property value by reflection setter of Orchard.ContentManagement.Records.ContentItemVersionRecord.Data

NHibernate.PropertyAccessException: could not set a property value by reflection setter of Orchard.ContentManagement.Records.ContentItemVersionRecord.Data ---> System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.Xml.XmlException: “<”(十六进制值 0x3C)是无效的特性字符。 第 1 行，位置 34192。 在 System.Xml.XmlTextReaderImpl.Throw(Exception e) 在 System.Xml.XmlTextReaderImpl.Throw(String res, String[] args) 在 System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr) 在 System.Xml.XmlTextReaderImpl.ParseAttributes() 在 System.Xml.XmlTextReaderImpl.ParseElement() 在 System.Xml.XmlTextReaderImpl.ParseElementContent() 在 System.Xml.XmlTextReaderImpl.Read() 在 System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r) 在 System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o) 在 System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o) 在 System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options) 在 System.Xml.Linq.XElement.Parse(String text, LoadOptions options) 在 Orchard.ContentManagement.FieldStorage.InfosetStorage.Infoset.set_Data(String value) 位置 D:\git\Orchard\src\Orchard\ContentManagement\FieldStorage\InfosetStorage\Infoset.cs:行号 22 在 Orchard.ContentManagement.Records.ContentItemVersionRecord.set_Data(String value) 位置 D:\git\Orchard\src\Orchard\ContentManagement\Records\ContentItemVersionRecord.cs:行号 18 --- 内部异常堆栈跟踪的结尾 --- 在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) 在 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) 在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) 在 System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture) 在 System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index) 在 NHibernate.Properties.BasicPropertyAccessor.BasicSetter.Set(Object target, Object value) --- 内部异常堆栈跟踪的结尾 --- 在 NHibernate.Properties.BasicPropertyAccessor.BasicSetter.Set(Object target, Object value) 在 NHibernate.Tuple.Entity.AbstractEntityTuplizer.SetPropertyValues(Object entity, Object[] values) 在 NHibernate.Tuple.Entity.PocoEntityTuplizer.SetPropertyValues(Object entity, Object[] values) 在 NHibernate.Persister.Entity.AbstractEntityPersister.SetPropertyValues(Object obj, Object[] values, EntityMode entityMode) 在 NHibernate.Engine.TwoPhaseLoad.InitializeEntity(Object entity, Boolean readOnly, ISessionImplementor session, PreLoadEvent preLoadEvent, PostLoadEvent postLoadEvent) 在 NHibernate.Loader.Loader.InitializeEntitiesAndCollections(IList hydratedObjects, Object resultSetId, ISessionImplementor session, Boolean readOnly) 在 NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer) 在 NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer) 在 NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer) 在 NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters) 在 NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes) 在 NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results) 在 NHibernate.Impl.CriteriaImpl.List(IList results) 在 NHibernate.Impl.CriteriaImpl.List[T]() 在 Orchard.ContentManagement.DefaultContentManager.GetManyImplementation(QueryHints hints, Action`2 predicate) 位置 D:\git\Orchard\src\Orchard\ContentManagement\DefaultContentManager.cs:行号 370 在 Orchard.ContentManagement.DefaultContentManager.Get(Int32 id, VersionOptions options, QueryHints hints) 位置 D:\git\Orchard\src\Orchard\ContentManagement\DefaultContentManager.cs:行号 168 在 Orchard.ContentManagement.DefaultContentManager.Get(Int32 id, VersionOptions options) 位置 D:\git\Orchard\src\Orchard\ContentManagement\DefaultContentManager.cs:行号 131 在 Orchard.Core.Contents.Controllers.AdminController.Edit(Int32 id) 位置 D:\git\Orchard\src\Orchard.Web\Core\Contents\Controllers\AdminController.cs:行号 314 在 lambda_method(Closure , ControllerBase , Object[] ) 在 System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) 在 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) 在 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) 在 System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) 在 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) 在 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() 在 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) 在 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() 在 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() 在 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() 在 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()`

**Comment by RockNHawk** [comment] 2019-03-23 07:32
Remove this content item from database can avoid this problem.

**Comment by sebastienros** [comment] 2019-03-28 19:04
How did this content got added to the database? Are you using some custom code to do it? The way Orchard does it makes everything XML encoded so this should not have happened. Or did you just use the content editor? In this case could you share the text you pasted?

**Comment by RockNHawk** [comment] 2019-03-28 23:52
> How did this content got added to the database? Are you using some custom code to do it? The way Orchard does it makes everything XML encoded so this should not have happened. Or did you just use the content editor? In this case could you share the text you pasted?

Hi, Thank you for taking the time to reply to me.

I just use the Orchard Blog module's rich text  content editor, no third-party module.

the step is:


- I copy this web page http://www.nanhua.com/Signals/ABC-7A.html (direct copy the web page content, not copy the page html) from browser and paste it into the editor (Chrome 69 Browser).
![image](https://user-images.githubusercontent.com/3222379/55199997-2a4d6d00-51f7-11e9-9584-0fbdf84f2ff2.png)
(copy the content contains '<5W')

- then paste into editor
![image](https://user-images.githubusercontent.com/3222379/55200008-39ccb600-51f7-11e9-930e-3c6584474be7.png)

 - click "Save"
![image](https://user-images.githubusercontent.com/3222379/55200005-36392f00-51f7-11e9-837a-0f1177610eea.png)

**Comment by RockNHawk** [comment] 2019-03-29 01:58
I think maybe the Encode Html method just encode the legal html tag , ignored the single '<' or '>' character, maybe add a str.Replace("<","&lt;").Replace(">","&gt;") after the Html Encode logic then will be OK ...

**Comment by sebastienros** [comment] 2019-04-04 19:17
It;s definitely not a standard &lt; 

![image](https://user-images.githubusercontent.com/1165805/55582102-7b67d000-56d3-11e9-8e7c-743ce1c1aafc.png)

I think we had a similar issue with some other chars by the past. @BenedekFarkas do you remember something like this, I think you were involved in the resolution too.

**Comment by BenedekFarkas** [comment] 2019-05-13 17:20
Sorry for replying just now. There's an open issue that I think cover this as well: #7560.

**Comment by sebastienros** [comment] 2019-05-16 19:11
Thanks, that's it

**Comment by sebastienros** [comment] 2019-05-16 19:11
Duplicate of #7560

**Closed as completed by sebastienros** 2019-05-16 19:11 UTC

**Comment by Piedone** [comment] 2019-05-21 17:00
BTW I tried to reproduce this error just by using the UI and couldn't. At one point the offending character gets encoded or something. However, if you assign the string directly to the infoset-backed property as under #7560 you can definitely get the exception.
