### ISSUE TITLE
404 error in workflow edit page for WorkflowsActivity-*.css files

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/Orchard#8008] opened 2018-04-02 05:14 UTC
1. go to workflow list page
2. edit or create one
3. F12
4. 404 error on WorkflowsActivity-*.css files

**Comment by sebastienros** [comment] 2018-04-05 19:09
Duplicate of https://github.com/OrchardCMS/Orchard/issues/7873

**Comment by BenedekFarkas** [comment] 2019-05-15 21:29
Fixed in #8201.

**Closed as completed by BenedekFarkas** 2019-05-15 21:29 UTC
