### ISSUE TITLE
Orchard should be able to use async controllers

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#5895] opened 2015-10-04 15:16 UTC
Thanks Nick pointing me to #2513 from 2012 which seems still not solved.
Some external assemblies are offering async controller and it is uneasy to insert them in Orchard.

**Comment by Piedone** [comment] 2015-10-06 07:37
So is this a duplicate of that other issue?

**Comment by sebastienros** [comment] 2015-10-08 19:48
Duplicate

**Closed by sebastienros** 2015-10-08 19:48 UTC
