### ISSUE TITLE
Orchard 1.10 home page 

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/Orchard#6669] opened 2016-03-28 18:09 UTC
well, I know this is normally my fault!
On my newly deployed 1.10 I receive error:
     Server Error in '/' Application
     The resource cannot be found. 'Requested URL: /'

However, I checked in Dashboard --> Aliasis --> Managed
and find the first entry with: "/    Content/Items/Display/12" 
when clicking this entry it shows me the correct HomePage! (needless to say that it works fine on my local system)
The log in the App-Data folder is empty!

Is there anything I need / could check! 
Thanks for your time and hints, ed

**Comment by sebastienros** [comment] 2016-03-28 18:27
> On my newly deployed 1.10 I receive error:

Is that an upgrade or a blank site?

**Comment by edikaufmann** [comment] 2016-03-28 19:47
sorry, I probably was not very clear:
- I downloaded the official 1.10 (web) from Github and migrated my private site into it. 
- it runs flawless on my system ; and as said: it opens the correct page in Aliases
... I'm not sure whether this answers your question!

**Comment by sebastienros** [comment] 2016-03-28 20:59
Try to open the content item, un-check the home page setting, publish then save it again as the homepage.
In the meantime we'll try to repro it with a migration from a previous version.

**Comment by donaldboulton** [comment] 2016-03-28 23:33
Same as [#6667](#6667)

**Comment by sebastienros** [comment] 2016-03-28 23:35
Duplicate of https://github.com/OrchardCMS/Orchard/issues/6667

**Closed by sebastienros** 2016-03-28 23:35 UTC
