### ISSUE TITLE
Editor Not showing correctly . 

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#7979] opened 2018-02-18 19:20 UTC
hi ,
I'm facing this annoying issue for a while . which i couldn't understand . 
<img src="https://i.imgur.com/ts7uJ5t.png" />

can any one explain why the Editor is not showing Correctly ? 

thanks !

**Comment by sfmskywalker** [comment] 2018-02-18 19:27
Anything in the F12 Developer Tools console window? Or perhaps a server-side error (see Log files)?

**Comment by ghost** [comment] 2018-02-18 19:28
No errors on the log

**Comment by ghost** [comment] 2018-02-18 19:29
and Some errors on the console : Couldn't find some css files . which i believe they r not the ones causing the issue .

**Comment by sfmskywalker** [comment] 2018-02-18 21:08
Can you provide repro steps with a clean Orchard installation and no custom modules?

**Comment by ghost** [comment] 2018-02-22 10:35
@sfmskywalker  its the current repo . i just re-clone it and its the same issue .

**Comment by sfmskywalker** [comment] 2018-02-22 11:44
Which branch?

**Comment by sfmskywalker** [comment] 2018-02-22 11:48
Never mind, I just tried it myself (dev branch) and can indeed repro the issue. I'll check the master and 1.10.x branches as well.

**Comment by sfmskywalker** [comment] 2018-02-22 11:52
The issue does not appear on 1.10.x. On dev I am seeing the 404s related to CSS files not being found. Although that could be irrelevant to this issue it's still disconcerting as those files should be available. I'll take a closer look.

**Comment by ghost** [comment] 2018-02-22 11:53
@sfmskywalker  i'm using the dev branch 1.9.2

**Comment by ghost** [comment] 2018-02-22 11:55
just to make sure is the bug exist on the layout module or the resources ?

**Comment by sfmskywalker** [comment] 2018-02-22 12:09
I think the missing CSS issue is different from the dialog positioning issue, but at the same time they may both be caused by the same underlying issue. Too early to tell. In any case, the former issue (menu stylesheet 404 due to incorrect path) has been reported in the past: #3310 which I just reopened.

**Comment by ghost** [comment] 2018-02-22 12:34
@sfmskywalker  the branch 1.10 has the editor working  well but still with that issue (css not found) , so i believe they r not causing the editor issue

**Comment by sfmskywalker** [comment] 2018-02-22 12:50
Interesting, I didn’t see either issues on 1.10.x. However I think you’re right that the two issues are unrelated.

**Comment by sebastienros** [comment] 2018-02-22 20:03
Also please show the network trace from Chrome debugging window.

**Comment by sfmskywalker** [comment] 2018-02-22 20:38
Found it, just pushed a fix.

**Closed as completed by sfmskywalker** 2018-02-22 20:38 UTC

**Comment by sfmskywalker** [comment] 2018-02-22 20:39
The issue was due to a change to the library picker's CSS file that added a height rule to some .overlay class. The Layout Dialog also uses a class named .overlay.

**Comment by ghost** [comment] 2018-02-23 09:20
works!  thanks .
