### ISSUE TITLE
Orchard admin: admin menu behavior

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#7019] opened 2016-07-01 18:53 UTC
- The admin menu is "sticky"-> this needs to be either a setting, or undone.
- The admin menu used to open sub menu items upon hover, allowing the parent menu item to be clickable for quick access. Currently, whenever a menu item has children, you are forced to expand the menu item before being able to access the feature.

**Comment by Skrypt** [comment] 2016-07-23 08:38
Before we could have a link on root menu items and the section was expandable by clicking only on the small arrow down icon. I think that if we want to make this to work on mobile devices : we can't still do that since we want people to be able to open submenus with their fingers. I suggest we keep it like it is right now for that purpose. Also, I added a small icon on the bottom of the menu to eventually implement a toggle of the left menu between the current implementation and an implementation with only icons "smaller width" for smartphones or mobile devices.

**Comment by Skrypt** [comment] 2016-08-12 16:34
As discussed with @sfmskywalker we will eventually have the option of toggling the left side menu to have the accordion or flyout version of it. This is a preference that should be kept in the admin cookie for each users.

**Comment by Skrypt** [comment] 2016-08-16 01:57
Closing this one as it is a duplicate of general todo task list

**Closed by Skrypt** 2016-08-16 01:57 UTC
Labels: Admin
