### ISSUE TITLE
ICultureSelector BrowserCultureSelector How I can use 

### ISSUE THREAD

**Issue by laurentb0204** [OrchardCMS/Orchard#6235] opened 2015-12-26 21:10 UTC
Hi,

I use the version 1.9.2 and fews ICultureSelector are implemented in solution, but I don't understand how we can use this... The are a setting to change ? Or work on this subject are not finished ?

Sincerely,

Laurent BROUCK

**Comment by bleroy** [comment] 2015-12-28 05:16
Please ask your questions on the forums or on Gitter.
I'm closing this, as it's not a bug.

**Closed by bleroy** 2015-12-28 05:16 UTC
