### ISSUE TITLE
Thread.CurrentThread.CurrentCulture is not set to the site default culture

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6636] opened 2016-03-22 21:18 UTC
Is it normal, I think that in the past the default site culture was applied to the current thread ?
Actually if I have an orchard site running on an US VM, which should stay in en-us for other reasons, orchard runs in en-us culture and complicates everything when the default site culture is not en-us.

**Comment by Skrypt** [comment] 2016-03-22 22:21
The thread culture is not changed. It's using your system culture.

**Comment by CSurieux** [comment] 2016-03-22 23:26
Yes it's the problem.

**Comment by DanielStolt** [comment] 2016-03-22 23:36
I think this is by design. This is why we have special abstractions to deal with culture-specific tasks rather than relying on the ambient thread culture. I think it may have to do with things like multi-tenancy but I'm not sure about the details.

**Comment by sebastienros** [comment] 2016-03-22 23:42
I assume the best suggestion here would be to create a feature that would set the current thread culture to the one from the CultureSelector, but internal we don't rely on the thread culture, it's just useful is you have components that use this.

**Comment by bleroy** [comment] 2016-03-22 23:51
If I may, associating the culture with the thread is sort of an anti-pattern on the part of .NET: there is no particular reason for this affinity, and it smells very much like a singleton (which are bad, m'kay?). Acquiring the culture from a finer-grained environment component that can be stubbed and replaced is the right thing to do, even if it's a little surprising for .NET developers who are used to finding it on the thread.

To take an example, imagine an implementation of a web server where requests are handled not by OS thread but by lightweight threads (like those in Go), or in an asynchronous mono-thread environment such as Node. Having the culture on the thread would put coupling at a completely irrelevant scope.

**Comment by DanielStolt** [comment] 2016-03-23 00:00
Agree with @bleroy 100%.

**Comment by CSurieux** [comment] 2016-03-23 00:18
The surprise comes when you have used a .net method relying on it which was ok in dev but on deploy. This seriously limits .net and force Orchard to rewrite all these méthode its way. I don't see the problem in setting this thread culture to site culture by defaut to benefit from all these apis and let the other Orchard users rely only on Orchard culture API to respect the clean concept...

**Comment by Skrypt** [comment] 2016-03-23 00:33
Je peux toujours écrire en français. Même dans une page HTML qui est marquée <html lang="en" ...
Un forum est un bel exemple de page HTML qui peut contenir du contenu multi-culturel. Dans ce cas-ci est-ce absolument nécessaire de changer complètement le thread du système pour me permettre à moi seulement d'écrire ce message ?

**Comment by DanielStolt** [comment] 2016-03-23 00:34
4 French guys, one Swedish... but for my benefit (and others potentially reading this thread) could we stick to English? :)

**Comment by Skrypt** [comment] 2016-03-23 00:36
Yes, sure. I was just making a statement in french to make an example if you can translate what I wrote :)

**Comment by DanielStolt** [comment] 2016-03-23 00:39
No sorry, my current thread is set to sv-SE. :)

**Comment by bleroy** [comment] 2016-03-23 04:08
He was saying that there are plenty of examples where changing the culture of the whole thread is vastly overkill. For example, this discussion has two different cultures on it. What culture should the thread have?

I'll add that the problem with using any method that relies on the thread culture will have the problems of a singleton: too rigid, hard to test, and sometimes just wrong.

**Comment by bleroy** [comment] 2016-03-23 04:14
Oh, and one more thing: there's a reason why all methods that have anything to do with culture have an overload that takes an explicit culture, and why coding guidelines, as well as Resharper and all similar tools will yell at you if you don't use those overloads. That reason is that the version that just takes the culture from the thread is bad practice. Being explicit is always better anyways.

**Comment by CSurieux** [comment] 2016-03-23 08:46
Bertrand has understood my concern but is locked in it singleton evangilian problem.
My concern is related to display and db storage of values depending of the current culture.
Not all .net methods have a culture parameter, take ToLongDateString, no version with culture (or VS is lost in translation).This is the reason why many .net methods had to be rewritten 'a la Orchard'.
Skrypt, it is not true that several cultures minded people could write in a forum using only one site culture, try to write spanish in fr-fr, yesterday I had to blog on a catalan artist named Miquel Barcelo, and I never found witch key to use on my french keyboard to enter the special accent on the last 'o' of its name (same in english). You can write but are limited by the sole culture of the site.

**Comment by TFleury** [comment] 2016-03-23 09:37
Duplicate of #5189

**Comment by CSurieux** [comment] 2016-03-23 09:50
Yes

**Comment by TFleury** [comment] 2016-03-23 10:09
Controller's `UpdateModel` and `TryUpdateModel` methods uses Thread culture to parse values. When you want to parse a decimal number property, you have to type the decimal separator based on hosting system culture instead of current site culture.

**Comment by CSurieux** [comment] 2016-03-23 11:04
Ha c'était donc pour ça :). 
Yes not very very friendly for non english guies....this is a larger concept Pb in Orchard: made by french for US :).

**Comment by Skrypt** [comment] 2016-03-23 13:59
I disagree if the page is in unicode it should be able to display most of common chars. Culture has nothing to do with your keyboard. You could easily have a spanish keyboard in a en-us Windows.

**Comment by CSurieux** [comment] 2016-03-23 15:50
Oui je sais depuis bientôt 36 ans... that is not the object of this thread.
Just to close this part, I never said you can't, I just said it is not user friendly and most of the time boring...my customers are not geeks, they want a tool easy to understand.

**Comment by bleroy** [comment] 2016-03-23 16:01
`date.ToLongDateString()` -> `date.ToString("D", culture)

If there's a bug in `UpdateModel` and `TryUpdateModel`, that should be fixed, but with an open mind and consistently with Orchard design, no necessarily mandating setting the thread culture. I haven't looked at the specifics yet, but I would be surprised if the culture couldn't be set in a clean and testable way.

And no, Orchard is not by French for US, it's by folks from all around the world, for everyone. The care that was put into this design (that I've explained) and others related to localization, as well as the number of translations contributed are testament to that. Once again, Christian projects his own prejudices onto the team.

**Comment by Skrypt** [comment] 2016-03-23 16:24
I agree that we should find a solution that everyone will agree on. @CSurieux  I don't believe I'm off topic, I was just trying to illustrate a simplification of the topic so that we can see a "big picture". And I apologize if I offended you in any way while doing so. Let's try to think straight here and try to avoid personnal interests.

And I agree with @bleroy

**Comment by CSurieux** [comment] 2016-03-23 16:45
Oh, you don't 'offend' anybody,  but I would have prefered you offended and read what I wrote.
Ok I prefer stopping all this, hope you will found the big picture somewhere. I think Bertrand will add the last words...

**Comment by Skrypt** [comment] 2016-03-23 16:58
@CSurieux Reading between the lines I understand that you would like that Orchard sets the Thread.CurrentThread.CurrentCulture to the default site culture. If this solutions gets voted and adopted democratically then it will happen. Though, if there is better solutions, opinions, we can suggest them here. In the end, if you really need this, you can also fork Orchard and use your own solution based on your own opinion. We are trying to help here, not the opposite.

**Comment by bleroy** [comment] 2016-03-23 17:07
Well, we don't vote on technical solutions, but well, yes, the goal is to fix a bug or find an adequate workaround. It might end up being done by tactically setting the thread culture, or it might be something cleaner. We'll see what we find by investigating further.

**Comment by Skrypt** [comment] 2016-03-23 17:16
Fair enough :)

**Comment by sebastienros** [comment] 2016-03-23 17:30
> the best suggestion here would be to create a feature that would set the current thread culture to the one from the CultureSelector, but internal we don't rely on the thread 

Quoting myself ...

**Comment by TFleury** [comment] 2016-03-23 19:01
Not relying on thread culture is a good practice and there are very few things relying on it in Orchard, but model binding is one (and it should be tricky to change that).
Actually thread culture choice is left to hosting environment and it can cause unpredictable behaviors. It should be set to a controlled value to avoid this, at worst to InvariantCulture.
I agree with Sébastien's suggestion.

**Closed** 2016-03-24 19:11 UTC
