### ISSUE TITLE
Why Orchard.Layouts does not define resources for AngularJS and other libraries?

### ISSUE THREAD

**Issue by armanforghani** [OrchardCMS/Orchard#5979] opened 2015-10-23 11:51 UTC
/cc @sfmskywalker, @sebastienros, @Piedone 

Orchard.Layouts creates bundle for AngularJS and some other libraries instead of defining resources. Please consider some other themes or modules depends on different versions of these libraries.
We can override a resource by specifying greater version number in ResourceManifest class but how can i override bundles?

I think this is absolutely wrong way.

**Comment by sfmskywalker** [comment] 2015-10-23 14:09
Yes, what we actually need is a dedicated module such as `Orchard.jQuery` that provides these reusable resources as proposed in issue #5438. We didn't want `Orchard.Layouts` to be the one providing that resource to others, but using it privately instead. This however causes an obvious issue if you write a custom part that also relies on AngularJS, in which case you would probably best include the scripts from `Orchard.Layouts` using `Script.Include` (providing the full relative path to the various scripts necessary).

Closing this one as a duplicate of #5438, since Orchard.Layouts will be updated to take advantage of the yet to be written `Orchard.Resources`.

**Closed by sfmskywalker** 2015-10-23 14:09 UTC

**Comment by armanforghani** [comment] 2015-10-23 19:46
@sfmskywalker I don't agree. What is the meaning of "using it privately"? 
The result of using it privately is this error: "Tried to load angular more than once."
Yes, You are right. We didn't want Orchard.Layouts to be the one providing that resource to others, but this module can define resource for now so that other developers be able to override that resource.
Please don't forget there are several custom modules and themes for Orchard in operational environments.
As i mentioned these modules may depend on newer version of AngularJS. For example i have several themes depend on AngularJS 1.4.6+. Do you think i can include AngularJS 1.3.3 from Orchard.Layouts?
What is the downside of resource definition until Client Libraries module will be available?
I'm surprised that you have closed this issue. I even think this issue needs hot patch because it has created problems in the functioning of many other modules.

**Comment by sfmskywalker** [comment] 2015-10-23 21:50
> What is the meaning of "using it privately"

I mean that it was not the module's purpose to provide AngularJS to others, hence no resource manifest is provided.

You seems to be saying that if we did provide a resource manifest, other modules would have been able to override that resource with a newer version of Angular. Do you know if people are doing the same with jQuery? I always assumed that modules providing back-end screens all used the jQuery version provided with Orchard - no overriding involved, because this becomes tricky very easily. So even if we provided an AngularJS resource manifest, the same principle would apply, where you would be "stuck" with the version of Angular that comes with Orchard.

>  i have several themes depend on AngularJS 1.4.6+. Do you think i can include AngularJS 1.3.3 from Orchard.Layouts?

In the case of themes, you can use any version of Angular you like - the Orchard.Layouts module does not include AngularJS scripts on the front-end - it's purely used for the layout editor in the back-end. So I don't foresee any conflicts here. Please do let me know if I'm wrong and share the actual issues and we can work them out.

> What is the downside of resource definition until Client Libraries module will be available?

1. It would require work that we already know would be undone.
2. This is more of a philosophical issue maybe, but the module is not intended to be a resource manifest provider of AngularJS - it just needs it itself. And since there is no `Orchard.Resources` module yet, it simply includes it for its own personal use. Granted, this does pose a challenge to module developers developing custom part editors that also want to use AngularJS - I would advise these part editors to include the same AngularJS files as the LayoutEditor (just as other modules reference the same jQuery version dictated by Orchard).

Other than that, I guess there's no technical downside to providing a resource manifest other than that you would still be "stuck" on the version dictated by Orchard (unless you *can* actually override resource manifests - I tried this a few years back by setting a newer Version, but that didn't do it for me - but, things may have changed since then).

> I'm surprised that you have closed this issue.

Well, despite the fact that your issue is absolutely valid, it will be solved by the other issue I referenced previously. No sense in keeping two same issues open, especially if the other issue provides the proper way to go about this situation.

> I even think this issue needs hot patch because it has created problems in the functioning of many other modules.

I'm pretty sure that whatever problems you are seeing regarding `Orchard.Layout` not providing a resource manifest for Angular can be solved otherwise and does not require any hot fixing of the Layouts module. But, please do share the issues you're seeing, I'm happy to help where I can.

**Comment by armanforghani** [comment] 2015-10-24 12:47
@sfmskywalker Thank you for taking the time and detailed answers.
> I mean that it was not the module's purpose to provide AngularJS to others, hence no resource manifest is provided.

I think the purpose of resource definition is not only providing the resource for others. I think it is a good practice because it allows management for other developers. Orchard.Blogs defines three resources ```BlogsAdmin, BlogsArchives, BlogsArchives```. Who may use this resource? no one. But this module allows you to manage these resources if necessary.
I think using resources privately specially about big frameworks such as AngularJS is a bad practice. Just imagine all modules follow such an approach.

> Do you know if people are doing the same with jQuery?

I don't know they do or not. Overriding resources is a useful feature in Orchard that many other CMSs have not it. On other hands you know AngularJS is a special case and has differences with jQuery.
Also please [click here](https://github.com/OrchardCMS/Orchard/issues/5283) to see other people use this feature even about jQuery.

> this becomes tricky very easily

Yes. Overriding a resource can cause problem for main module but please don't forget the developer of a site have some custom private modules or themes and he (she) can override resources If any problem do not come to the main module. Yes, overriding a resource for a module and publishing it in gallery is very bad practice. 

> In the case of themes, you can use any version of Angular you like - the Orchard.Layouts module does not include AngularJS scripts on the front-end - it's purely used for the layout editor in the back-end. So I don't foresee any conflicts here. Please do let me know if I'm wrong and share the actual issues and we can work them out.

Yes, I know it's purely used for the layout editor in the back-end. but i develop some advanced Admin themes depend on AngularJS like many popular themes that exist today. Also i have several custom modules using AngularJS.

> No sense in keeping two same issues open, especially if the other issue provides the proper way to go about this situation.

I think the issue you referenced is an improvement (Refactoring) issue but this is bug or conflict issue although you do not agree with this.

Dear Sipke, I understand your approach but in operational environment there are some differences. I have several sites with more than 36 custom modules and three custom back-end theme. Orchard.Layouts is very useful and modern feature and i wish to use it. but it drops all my custom modules and themes for this simple conflict.

I hate modifying the source code but this issue forces me to modifying the code for personal usage and this creates difficulties for the maintenance.

Anyway you are the Boss. 
Thank you so much for developing Orchard.Layouts. It's really good feature. The new generation of content management.

**Comment by sfmskywalker** [comment] 2015-10-24 15:41
> I think using resources privately specially about big frameworks such as AngularJS is a bad practice

I agree, this is why we want #5438 to be done.

> Anyway you are the Boss. 

No I'm not. :)

So basically it sounds to me that we both agree AngularJS should be provided as a resource. The issue #5438 has been triaged and ready to be implemented. Although it has been assigned to @DanielStolt, perhaps you'd like to get started with it and submit a PR?

Thanks, really glad to hear it. :)

**Comment by armanforghani** [comment] 2015-10-24 16:41
I will think about how we should implement this module. There are some issues for using resources such as jQueryUI, Bootstrap, etc. in RTL direction. I think these resource definition must be culture aware.

Thank you very much for your answers.
