### ISSUE TITLE
Saving Layout makes Content Item (Page) that uses Layout revert to prior version

### ISSUE THREAD

**Issue by remesq** [OrchardCMS/Orchard#5337] opened 2015-05-31 15:09 UTC
Sorry if I am not explaining this well, but this issue cropped up early on my setting up a site, and I just deleted ~/AppData and started over. The problem still exists, however.

FIRST SITE: I created a Master Layout and then applied it to the stock "Welcome to Orchard" page item. However, I could not move the grid/row/column/html to one of the areas I created in my Layout.  So, I re-created those elements and put them where I wanted them to be in the Layout. If ever I went back and tweaked the Layout, then the Page item would "revert back" (it seems to the prior version). In other words, the HTML elements I created and placed would not be there, and I would have the old "Welcome to Orchard" elements. Thinking it had something to do with the fact that the Welcome text is hard-coded in the recipe, I just thought to start from scratch, delete ~/AppData and create a new Content Page item.

SECOND SITE: I created a new Master Layout. I created a New Page and applied the Master Layout. I set this page to "Home". It was able to display, but then when I tweaked the Layout and published it, the new Page I created seems to have reverted to a prior version. In other words, it was no longer ticked as "Home", so when viewed I get a resource not available message. I can go back and tick "Home" on the Page item and then it displays fine. However, any further changes to the Master Layout and it REVERTS BACK.

Ouch. Any thoughts.

**Comment by sfmskywalker** [comment] 2015-05-31 18:09
Obviously a bug. Thanks for the detailed repro steps!

**Comment by remesq** [comment] 2015-06-01 13:09
FYI: I do not know if this has anything to do with the problem, but I was only using the Content Zone in my Theme (I have no other Zones at all). I created three grids in my Master Layout and gave them ID's of Grid-Header, Grid-Content and Grid-Footer. I also modified the Page.Layout.cshtml (no CSS class) , ~/Elements/Grid.cshtml (class=container) and ~/Elements/Column.cshtml (class=col-md-).

**Comment by sfmskywalker** [comment] 2015-07-02 09:38
I can reproduce that it removes the homepage setting, but I can't reproduce that it reverts to a previous version. while investigating the "homepage setting being lost" issue, I noticed that whenever you create a new page and set it to be the homepage, and *Save* the page (not using the *Publish Now* button), the setting won't be persisted. Only when you publish the page will it become the homepage. So I'm suspecting this behavior has something to do with the issue, and should probably be solved first. Looking into it.

**Comment by sfmskywalker** [comment] 2015-07-02 10:46
The issue was that when publishing the layout template that is used by the homepage, the layout part handler would create a draft first before applying the updated layout template. The DisplayAlias for this draft would be "" since it is the current homepage. However, when publishing a content item where its DisplayAlias is an empty string, the autoroute part handler will generate a new alias. At this point, no content item will be set as the homepage anymore, since the only content item with an empty DisplayAlias now has a non-empty alias.
The way to fix this is to make sure the DisplayAlias is set to "/" (in case the content item being published is the currenthomepage) before publishing it.

**Comment by sfmskywalker** [comment] 2015-07-02 10:46
Fixed in 2873eb89913e8ab4ed6814c28303879489a00f27.

**Closed by sfmskywalker** 2015-07-02 10:46 UTC
Labels: bug, Layouts
