### ISSUE TITLE
Mistake in constructing the breadcrumbs

### ISSUE THREAD

**Issue by neTp9c** [OrchardCMS/Orchard#5624] opened 2015-08-07 20:34 UTC
There is an option in MenuWidget module: Check to render the current content item as the last element.
If this option is uncheched that Orchard may removes not current content item from breadcrumbs.

It happens because orchard looking for active menu items by the url and considers the menu item as active when the requested page url starts from menu item url. (it's cool, but it does not work correctly with the mentioned option). Then orchard removes last item from breadcrumbs. But last item can be not current (when current page isn't added to a menu).

To fix this mistake:
1.Add a property to Orchard.UI.Navigation.MenuItem class

```
public bool Current { get; set; }
```

2.Change method of Orchard.UI.Navigation.NavigationHelper class

```
private static Stack<MenuItem> SetSelectedPath(IEnumerable<MenuItem> menuItems, HttpRequestBase currentRequest, RouteValueDictionary currentRouteData, bool compareUrls) {
            foreach (MenuItem menuItem in menuItems) {
                Stack<MenuItem> selectedPath = SetSelectedPath(menuItem.Items, currentRequest, currentRouteData, compareUrls);
                if (selectedPath != null) {
                    menuItem.Selected = true;
                    menuItem.Current = false;
                    selectedPath.Push(menuItem);
                    return selectedPath;
                }

                // compare route values (if any) first
                // if URL string comparison is used it means all previous route matches failed, thus no need to do them twice
                bool match = !compareUrls && menuItem.RouteValues != null && RouteMatches(menuItem.RouteValues, currentRouteData);
                bool current = true;

                // if route match failed, try comparing URL strings, if
                if (currentRequest != null && !match && compareUrls) {
                    string appPath = currentRequest.ApplicationPath ?? "/";
                    string requestUrl = currentRequest.Path.StartsWith(appPath) ? currentRequest.Path.Substring(appPath.Length) : currentRequest.Path;

                    string modelUrl = menuItem.Href.Replace("~/", appPath);
                    modelUrl = modelUrl.StartsWith(appPath) ? modelUrl.Substring(appPath.Length) : modelUrl;

                    if (requestUrl.Equals(modelUrl, StringComparison.OrdinalIgnoreCase)) {
                        match = true;
                    }
                    else if ((!string.IsNullOrEmpty(modelUrl) && requestUrl.StartsWith(modelUrl + "/", StringComparison.OrdinalIgnoreCase)))
                    {
                        match = true;
                        current = false;
                    }
                }

                if (match) {
                    menuItem.Selected = true;
                    menuItem.Current = current;

                    selectedPath = new Stack<MenuItem>();
                    selectedPath.Push(menuItem);
                    return selectedPath;
                }
            }

            return null;
        }
```

3.Аdd a check of this property before deleting current page from breadcrumbs (change Display function in Orchard.Core.Navigation.Drivers.MenuWidgetPartDriver class)

```
// inject the current page
                    if (!part.AddCurrentPage && selectedPath != null && result[result.Count - 1].Current)
                    {
                        result.RemoveAt(result.Count - 1);
                    }
```

**Comment by BenedekFarkas** [comment] 2019-08-23 10:05
Closing this and the PR: I couldn't reproduce the issue, so I'm assuming that changes made since then (probably #6899) fixed this too.

**Closed by BenedekFarkas** 2019-08-23 10:05 UTC
