### ISSUE TITLE
Admin Theme - RTL - User dropdown menu overlapped by page scrollbar

### ISSUE THREAD

**Issue by ifle** [OrchardCMS/Orchard#7292] opened 2016-10-11 09:21 UTC
![orchard-rtl-issue25](https://cloud.githubusercontent.com/assets/1140474/19265276/30df2744-8fad-11e6-907e-0b474d43a376.jpg)

**Comment by sfmskywalker** [comment] 2016-10-13 02:43
I don't see that issue. This is what I see:

![image](https://cloud.githubusercontent.com/assets/938393/19334866/0d1803e6-90cd-11e6-9564-524910dc1466.png)

Can you please pull latest, clear your browser's cache, and let me know if you are still seeing this issue? I'm closing this issue for now since I can't reproduce it, but will reopen it if you are still seeing the same issue.

Thanks!

**Comment by ifle** [comment] 2016-10-13 05:38
I rechecked both on IE 11 and Chrone and can't reproduce this is issue. 

Regards,

Igor

**Comment by sfmskywalker** [comment] 2016-10-13 16:35
Thanks for checking

**Closed by sfmskywalker** 2016-10-13 16:35 UTC
Labels: Admin, bug
