### ISSUE TITLE
Can't enable/set current new themes - Orchard v1.10.1.0

### ISSUE THREAD

**Issue by schoe311** [OrchardCMS/Orchard#6904] opened 2016-05-18 18:15 UTC
I have created new themes from the command line tool from a clean install of the source.  Have ran the site in debug mode, gone through setup and enabled code generation.

After running the codegen theme line, the new theme will show up when clicking on "Themes" in admin, however when I try to enable or set current the newly created theme, I get the following:

An unhandled exception has occurred and the request was terminated. Please refresh the page. If the error persists, go back
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object. at Orchard.Themes.Services.ThemeService.EnableThemeFeatures(String themeName) at Orchard.Themes.Controllers.AdminController.Activate(String themeId) at lambda_method(Closure , ControllerBase , Object[] ) at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()

**Comment by infofromca** [comment] 2016-05-18 21:08
From Orchard.exe?
#6901 reports that it only happened in orchard.exe

**Comment by konstrui** [comment] 2016-05-25 09:25
Can confirm this issue with Orchard 1.10.x.

**Comment by konstrui** [comment] 2016-05-25 09:33
If I use this code:

`codegen theme MyThemeName`

Then inside the Theme.txt this line was added:

   `BaseTheme: $$BaseTheme$$`

This causes troubles, although I did not figured out what the problem is.
By removing this line I can active the theme without problems.

**Comment by rtpHarry** [comment] 2016-05-28 10:28
I've done the following with 1.10.x branch:

    1. git clone 1.10.x branch
    1. run the site so it sets up a default tenant
    1. opened `orchard.exe`
    1. `feature enable Orchard.CodeGeneration`
    1. `codegen theme MyThemeName` - no $$BaseTheme$$ in the theme.txt
    1. from #6901 `codegen theme MeiyinTheme /CreateProject:true /IncludeInSolution:true /BasedOn:TheThemeMachine`
    1. from #6901 `codegen theme MeiyinTheme /IncludeInSolution:true /CreateProject:true`
    1. `codegen theme basedontheme /BasedOn:TheThemeMachine`

No $$BaseTheme$$ placeholder left behind, no exceptions when activating the themes.

I will retry with 1.10.1 but I'm out of time now for the next few days.

**Comment by sebastienros** [comment] 2017-01-03 23:36
Closing as we don't repro in 1.10.x as per @rtpHarry

**Closed by sebastienros** 2017-01-03 23:36 UTC
Labels: high
