### ISSUE TITLE
Gulp is not seeing changes made in LESS import files

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6230] opened 2015-12-23 13:36 UTC
We have 2 options, either touch all ''main' files using the changed import files, either do a rebuild but here many changes in the solution and commit pb later...
This seems to be a general Gulp Pb with import files.

**Comment by DanielStolt** [comment] 2015-12-23 22:28
Duplicate of #5849 (also opened by you).

**Closed by DanielStolt** 2015-12-23 22:28 UTC
