### ISSUE TITLE
Translation of widget with LocalizationPart throws System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by loshuliveros** [OrchardCMS/Orchard#5501] opened 2015-07-10 20:28 UTC
I use clean installation of Orchard 1.9.1

Line 8:
Line 9: @Html.LabelFor(widget => widget.LayerId, T("Layer"))
Line 10: @Html.DropDownListFor(widget => widget.LayerId, new SelectList(Model.AvailableLayers, "Id", "Name"))
Line 11: @T("The Layer where the Widget will be rendered.")
Line 12:
Source File: src\Orchard.Web\Modules\Orchard.Widgets\Views\EditorTemplates\Parts.Widgets.WidgetPart.cshtml Line: 10

[NullReferenceException: Object reference not set to an instance of an object.]
Orchard.Widgets.Models.WidgetPart.get_LayerId() +128

[TargetInvocationException: Property accessor 'LayerId' on object 'Orchard.Widgets.Models.WidgetPart' threw the following exception:'Object reference not set to an instance of an object.']
System.ComponentModel.ReflectPropertyDescriptor.GetValue(Object component) +525
System.Web.Mvc.ViewDataInfo.get_Value() +34
System.Web.Mvc.Html.SelectExtensions.SelectInternal(HtmlHelper htmlHelper, ModelMetadata metadata, String optionLabel, String name, IEnumerable1 selectList, Boolean allowMultiple, IDictionary2 htmlAttributes) +288
System.Web.Mvc.Html.SelectExtensions.DropDownListFor(HtmlHelper1 htmlHelper, Expression1 expression, IEnumerable1 selectList, String optionLabel, IDictionary2 htmlAttributes) +130
System.Web.Mvc.Html.SelectExtensions.DropDownListFor(HtmlHelper1 htmlHelper, Expression1 expression, IEnumerable`1 selectList) +80
ASP._Page_Modules_Orchard_Widgets_Views_EditorTemplates_Parts_Widgets_WidgetPart_cshtml.Execute() in src\Orchard.Web\Modules\Orchard.Widgets\Views\EditorTemplates\Parts.Widgets.WidgetPart.cshtml:10
System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +253
System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +148
System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +122
System.Web.Mvc.Html.RenderPartialExtensions.RenderPartial(HtmlHelper htmlHelper, String partialViewName) +96
Orchard.Core.Shapes.CoreShapes.RenderInternal(HtmlHelper Html, TextWriter Output, String TemplateName, Object Model, String Prefix) in src\Orchard.Web\Core\Shapes\CoreShapes.cs:766
Orchard.Core.Shapes.CoreShapes.EditorTemplate(HtmlHelper Html, TextWriter Output, String TemplateName, Object Model, String Prefix) in src\Orchard.Web\Core\Shapes\CoreShapes.cs:754

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +128
System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +146
System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +34
Orchard.DisplayManagement.Descriptors.ShapeAttributeStrategy.ShapeAttributeBindingStrategy.PerformInvoke(DisplayContext displayContext, MethodInfo methodInfo, Object serviceInstance) in src\Orchard\DisplayManagement\Descriptors\ShapeAttributeStrategy\ShapeAttributeBindingStrategy.cs:64
Orchard.DisplayManagement.Descriptors.ShapeAttributeStrategy.<>c__DisplayClass4.b__3(DisplayContext context) in src\Orchard\DisplayManagement\Descriptors\ShapeAttributeStrategy\ShapeAttributeBindingStrategy.cs:55
Orchard.DisplayManagement.Descriptors.<>c__DisplayClass5.b__2(DisplayContext displayContext) in src\Orchard\DisplayManagement\Descriptors\ShapeAlterationBuilder.cs:56
Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context) in src\Orchard\DisplayManagement\Implementation\DefaultDisplayManager.cs:203
Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context) in src\Orchard\DisplayManagement\Implementation\DefaultDisplayManager.cs:99
Orchard.DisplayManagement.Implementation.DisplayHelper.ShapeExecute(Object shape) in src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:86
Orchard.DisplayManagement.Implementation.DisplayHelper.Invoke(String name, INamedEnumerable`1 parameters) in src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:44
Orchard.DisplayManagement.Implementation.DisplayHelper.TryInvoke(InvokeBinder binder, Object[] args, Object& result) in src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:29
CallSite.Target(Closure , CallSite , Object , Object ) +239
Orchard.Core.Shapes.CoreShapes.ContentZone(Object Display, Object Shape, TextWriter Output) in src\Orchard.Web\Core\Shapes\CoreShapes.cs:286

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +128
System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +146
System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +34
Orchard.DisplayManagement.Descriptors.ShapeAttributeStrategy.ShapeAttributeBindingStrategy.PerformInvoke(DisplayContext displayContext, MethodInfo methodInfo, Object serviceInstance) in src\Orchard\DisplayManagement\Descriptors\ShapeAttributeStrategy\ShapeAttributeBindingStrategy.cs:64
Orchard.DisplayManagement.Descriptors.ShapeAttributeStrategy.<>c__DisplayClass4.b__3(DisplayContext context) in src\Orchard\DisplayManagement\Descriptors\ShapeAttributeStrategy\ShapeAttributeBindingStrategy.cs:55
Orchard.DisplayManagement.Descriptors.<>c__DisplayClass5.b__2(DisplayContext displayContext) in src\Orchard\DisplayManagement\Descriptors\ShapeAlterationBuilder.cs:56
Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context) in src\Orchard\DisplayManagement\Implementation\DefaultDisplayManager.cs:203
Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context) in src\Orchard\DisplayManagement\Implementation\DefaultDisplayManager.cs:99
Orchard.DisplayManagement.Implementation.DisplayHelper.ShapeExecute(Object shape) in src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:86
Orchard.DisplayManagement.Implementation.DisplayHelper.Invoke(String name, INamedEnumerable1 parameters) in src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:44 Orchard.DisplayManagement.Implementation.DisplayHelper.TryInvoke(InvokeBinder binder, Object[] args, Object& result) in src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:29 CallSite.Target(Closure , CallSite , Object , Object ) +239 ASP._Page_Modules_Orchard_Widgets_Views_Widget_Edit_cshtml.Execute() in src\Orchard.Web\Modules\Orchard.Widgets\Views\Widget.Edit.cshtml:3 System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +253 System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +148 System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +122 System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData) +137 Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.Render(ShapeDescriptor shapeDescriptor, DisplayContext displayContext, HarvestShapeInfo harvestShapeInfo, HarvestShapeHit harvestShapeHit) in src\Orchard\DisplayManagement\Descriptors\ShapeTemplateStrategy\ShapeTemplateBindingStrategy.cs:151 Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.<>c__DisplayClass28.<Discover>b__15(DisplayContext displayContext) in src\Orchard\DisplayManagement\Descriptors\ShapeTemplateStrategy\ShapeTemplateBindingStrategy.cs:133 Orchard.DisplayManagement.Descriptors.<>c__DisplayClass5.<BoundAs>b__2(DisplayContext displayContext) in src\Orchard\DisplayManagement\Descriptors\ShapeAlterationBuilder.cs:56 Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context) in src\Orchard\DisplayManagement\Implementation\DefaultDisplayManager.cs:203 Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context) in src\Orchard\DisplayManagement\Implementation\DefaultDisplayManager.cs:99 Orchard.DisplayManagement.Implementation.DisplayHelper.ShapeExecute(Object shape) in src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:86 Orchard.DisplayManagement.Implementation.DisplayHelper.Invoke(String name, INamedEnumerable1 parameters) in src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:44
Orchard.DisplayManagement.Implementation.DisplayHelper.TryInvoke(InvokeBinder binder, Object[] args, Object& result) in src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:29
CallSite.Target(Closure , CallSite , Object , Object ) +239
System.Dynamic.UpdateDelegates.UpdateAndExecute2(CallSite site, T0 arg0, T1 arg1) +701
ASP._Page_Modules_Orchard_Localization_Views_admin_Translate_cshtml.Execute() in src\Orchard.Web\Modules\Orchard.Localization\Views\Admin\Translate.cshtml:7
System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +253
System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +148
System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +122
Orchard.Mvc.ViewEngines.ThemeAwareness.<>c__DisplayClass7.b__5(ViewContext viewContext, TextWriter writer, IViewDataContainer viewDataContainer) in src\Orchard\Mvc\ViewEngines\ThemeAwareness\LayoutAwareViewEngine.cs:59
Orchard.Mvc.ViewEngines.ThemeAwareness.LayoutView.Render(ViewContext viewContext, TextWriter writer) in src\Orchard\Mvc\ViewEngines\ThemeAwareness\LayoutAwareViewEngine.cs:90
System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +375
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +90 System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833 System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833 System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833 System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833 System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833 System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833 System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833
System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833 System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList1 filters, ActionResult actionResult) +81
System.Web.Mvc.Async.<>c__DisplayClass21.b__1e(IAsyncResult asyncResult) +186
System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
System.Web.Mvc.Controller.b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
System.Web.Mvc.Async.WrappedAsyncVoid1.CallEndDelegate(IAsyncResult asyncResult) +65 System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53 System.Web.Mvc.Async.WrappedAsyncVoid1.CallEndDelegate(IAsyncResult asyncResult) +36
System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
System.Web.Mvc.MvcHandler.b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +44
System.Web.Mvc.Async.WrappedAsyncVoid1.CallEndDelegate(IAsyncResult asyncResult) +65 System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38 System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task`1 promise, Boolean requiresSynchronization) +77
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13844756
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
Orchard.Mvc.Routes.<b__0>d__4.MoveNext() in src\Orchard\Mvc\Routes\ShellRoute.cs:174
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13844756
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
Orchard.Owin.<b__0>d__2.MoveNext() in src\Orchard\Owin\OrchardMiddleware.cs:17
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13844756
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
Orchard.Mvc.Routes.d__7.MoveNext() in src\Orchard\Mvc\Routes\ShellRoute.cs:181
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13844756
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +69
System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +399
System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +157

**Comment by Skrypt** [comment] 2015-07-11 04:01
Duplicate of #5031
Will need to find time to fix this one. This is getting reported often.

**Comment by loshuliveros** [comment] 2015-07-11 18:05
Any quick fix/hack? I realy need it soon, later i will apply regular update...

**Comment by loshuliveros** [comment] 2015-07-12 07:59
I Fixed it temporary this way - in Orchard.Localization.Controllers.AdminController:

<code>
[ValidateInput(false)]
    public class AdminController : Controller, IUpdateModel {
        private readonly IContentManager _contentManager;
        private readonly ILocalizationService _localizationService;

        public AdminController(
            IOrchardServices orchardServices,
            IContentManager contentManager,
            ILocalizationService localizationService,
            IShapeFactory shapeFactory) {
            _contentManager = contentManager;
            _localizationService = localizationService;
            T = NullLocalizer.Instance;
            Services = orchardServices;
            Shape = shapeFactory;
        }

        dynamic Shape { get; set; }
        public Localizer T { get; set; }
        public IOrchardServices Services { get; set; }

        public ActionResult Translate(int id, string to) {
            var masterContentItem = _contentManager.Get(id, VersionOptions.Latest);
            if (masterContentItem == null)
                return HttpNotFound();

            var masterLocalizationPart = masterContentItem.As<LocalizationPart>();
            if (masterLocalizationPart == null)
                return HttpNotFound();

            // Check is current item stll exists, and redirect.
            var existingTranslation = _localizationService.GetLocalizedContentItem(masterContentItem, to);
            if (existingTranslation != null) {
                var existingTranslationMetadata = _contentManager.GetItemMetadata(existingTranslation);
                return RedirectToAction(
                    Convert.ToString(existingTranslationMetadata.EditorRouteValues["action"]),
                    existingTranslationMetadata.EditorRouteValues);
            }

            var contentItemTranslation = _contentManager.New<LocalizationPart>(masterContentItem.ContentType);
            contentItemTranslation.MasterContentItem = masterContentItem;

            var content = _contentManager.BuildEditor(contentItemTranslation);

            // START MY CODE
            var masterWidgetPart = masterContentItem.As<WidgetPart>();
            if (masterWidgetPart != null) {
                var parts = ((IContent)contentItemTranslation).ContentItem.Parts;
                if (parts != null) {
                    var widgetPart = parts.Single(x => x.PartDefinition.Name == "WidgetPart").As<WidgetPart>();
                    widgetPart.LayerPart = masterWidgetPart.LayerPart;
                    widgetPart.Name = masterWidgetPart.Name;
                    widgetPart.Position = masterWidgetPart.Position;
                    widgetPart.RenderTitle = masterWidgetPart.RenderTitle;
                    widgetPart.Title = masterWidgetPart.Title;
                    widgetPart.Zone = masterWidgetPart.Zone;
                }
            }
            // ENDMY CODE

            return View(content);
        }
</code>

**Comment by Piedone** [comment] 2015-07-12 21:22
Closing as duplicate.

**Closed by Piedone** 2015-07-12 21:22 UTC

**Comment by Skrypt** [comment] 2015-07-15 16:06
@loshuliveros the fix should'nt need to reference the Widget module into the Localization module. It's supposed to work with all content types. I will look at it today.

**Comment by loshuliveros** [comment] 2015-07-16 07:10
@Skrypt thanks for info, i thought about it shouldn't be referenced...
