### ISSUE TITLE
Orchard.Layouts css class should be prefixed by .layout-designer

### ISSUE THREAD

**Issue by urbanit** [OrchardCMS/Orchard#5728] opened 2015-09-01 16:26 UTC
In order not to mess up with clent theme classes with same names, think that Orchard.Layouts css class should be prefixed by .layout-designer.

For example, in default-grid.css instead of ".row" shoud use ".layout-designer .row" otherwise in a bootastrap theme,  it overrides bootstrap row class.

cc:/ @sfmskywalker @DanielStolt

**Comment by bleroy** [comment] 2015-09-10 21:49
Well, you should override parts.layout in order to suppress the inclusion of that script file anyway, if you're using Bootstrap's grid system.

**Comment by rtpHarry** [comment] 2015-09-11 09:24
Ideally there should be a site setting "Use Bootstrap 3" as this is the pretty much the first thing everyone is going to have to mod in order to make the feature useful :)

**Comment by urbanit** [comment] 2015-09-11 11:48
Ideally, backend styling should not mess up frontend theme by any means. Maybe, not requesting default-grid.css as client is the solution.
@bleroy this should be used out of the box, although your solution is accurate for the time being.
@rtpHarry there are many ui frameworks that use .row class, not only bootstrap 3 :-)

**Comment by rtpHarry** [comment] 2015-09-11 11:50
No, I'm pretty sure Bootstrap have filed a trademark claim for `.row`... :)

**Comment by Piedone** [comment] 2015-09-11 11:57
FYI you can totally de-active the Layouts grid by overriding the CSS file (default-grid.css?) in your theme/dependent module even with an empty file.

**Comment by sfmskywalker** [comment] 2015-09-11 12:00
Would it be an idea to not include the default-grid.css from the module's view, but from TheThemeMachine? In other words, using the default-grid would become opt-in, instead of opt-out.

**Comment by urbanit** [comment] 2015-09-11 12:25
@rtpHarry lol
@piedone sure
@sipke sounds good to me

**Comment by rtpHarry** [comment] 2015-09-11 14:29
I keep thinking about the user that isn't a developer. If you install the theme via the gallery then should Orchard let you toggle the grid include via the admin panel? 

I think @sfmskywalker was right that it's the theme author's responsibility to support modifications to the Layouts module in their theme (#5788).

If we make the grid opt-in via code only then it breaks compatibility in every theme that you can currently install via the gallery.

**Comment by bleroy** [comment] 2015-09-11 16:57
Until we decide to declare that Bootstrap is our default choice for front-end themes, we can't bake the Bootstrap grid in. And if we decide that BS is the default, then the default theme that Orchard ships with must be a Bootstrap theme. I'm all for it, but it's a bigger decision than this bug encompasses.

**Comment by urbanit** [comment] 2015-09-11 18:16
I was thinking about a solution that modules expose only "client" stylesheets and hide "admin" ones...

**Comment by sfmskywalker** [comment] 2015-09-11 18:17
You mean there's a problem that modules have admin stylesheets?

**Comment by urbanit** [comment] 2015-09-11 18:31
Yes, I think there should be a way to distinct them.

**Comment by urbanit** [comment] 2015-09-11 18:32
And, there are unnecessary calls to "admin" stylesheets client-side.

**Comment by sfmskywalker** [comment] 2015-09-11 18:43
I'm still not sure I understand what problem you're creating a solution for.

But if you're seeing calls to admin specific stylesheets then that's most likely a bug that is probably caused by some view including the wrong style.

Could you please tell me what admin stylesheet is being loaded from the front-end?

**Comment by urbanit** [comment] 2015-09-11 18:49
For example, I have a site with bootstrap theme. When I create a page with layout, default-grid.css row style overrides bootstrap one. @bleroy and @piedone solutions work but in fact I do not need to load default-grid.css...

**Comment by sfmskywalker** [comment] 2015-09-11 18:54
Ah. But default-grid.css is intended to be loaded on the front-end so that the layout looks good in themes that don't use a grid system, such as TheThemeMachine. If your theme does use a grid system, then the way to handle that is by creating shape overrides, as you would do with any other shape template that needs to be tuned for your theme.

**Comment by urbanit** [comment] 2015-09-11 19:00
That's clear. If it is intended behavior, it is ok. But still, sounds strange to me. It was just a point,  feel free to close issue. Cheers.

**Comment by sfmskywalker** [comment] 2015-09-11 19:13
I get that it would sound strange if you consider "default-grid.css" to be an admin stylesheet, but it really isn;t intended just for the admin. Like Bootstrap, which could be used for both back end as well as front end, "default-grid.css" is a general-purpose, lightweight grid system. It's useful for the back end as well as the front end, as it doesn't require a dependency on heavier-weight grid systems.

**Comment by sebastienros** [comment] 2015-09-11 21:05
I think the best solution is to have the `default-grid.css` inside TheThemeMachine and inside the module so that the admin can require it. This way a child theme can override the content, and a new theme doesn't have to inject it.

**Comment by bleroy** [comment] 2015-09-11 21:17
Looks like a good idea, but may break existing themes that rely on it.

**Comment by sebastienros** [comment] 2015-09-11 21:40
Yes, it's potentially breaking, this is why I assigned to dev. We'll have to document it in the release notes.

**Comment by sebastienros** [comment] 2015-09-11 21:40
Actually moving it to 1.10.

**Closed** 2016-01-13 23:47 UTC
