### ISSUE TITLE
How to wait for recipe execution or execute it sinchronously

### ISSUE THREAD

**Issue by luciofassio** [OrchardCMS/Orchard#8136] opened 2018-11-05 09:43 UTC
In my migrations.cs I'm creating a few taxonomies with a recipe and creating a content type which refers to them via taxonomy fields.

Everything works except the fact that the recipe is executed asynchronously and so when i try taxonomyService.GetTaxonomyByName it fails because the recipe has not been executed yet.

Is there a way to wait execution until the recipe finishes, maybe using executionId as parameter? Or to execute a recipe synchronously?  I watched for it in the Orchard code but was unable to find. The code is enclosed.

Thank you in advance.

Lucio Fassio. 

namespace Inva.BandiAvvisi {
    public class Migrations : DataMigrationImpl {
        private readonly IRecipeManager _recipeManager;
        private readonly IShellDescriptorManager _shellDescriptorManager;
        private readonly IRecipeParser _recipeParser;
        private readonly IWebSiteFolder _webSiteFolder;
        private readonly ITaxonomyService _taxonomyService;

        public Migrations(
            IRecipeParser recipeParser,
            IRecipeManager recipeManager,
            IShellDescriptorManager shellDescriptorManager,
            IWebSiteFolder webSiteFolder,
            ITaxonomyService taxonomyService)
        {

            _recipeManager = recipeManager;
            _shellDescriptorManager = shellDescriptorManager;
            _recipeParser = recipeParser;
            _webSiteFolder = webSiteFolder;
            _taxonomyService = taxonomyService;
        }

        public int Create() {
            // create taxonomies with a recipe
            var recipe = LoadRecipe("/Recipes/tassonomie-bandi.recipe.xml");
            var exid = Execute(recipe);

            // i need some code to wait execution here until the recipe ends
            // otherwise these statements won't work

            //var taxDestinatari = _taxonomyService.GetTaxonomyByName("Destinatari");
            //var taxAreeTematiche = _taxonomyService.GetTaxonomyByName("Aree tematiche");
            //var taxFondiProgrammi = _taxonomyService.GetTaxonomyByName("Fondi e programmi");
            
            // create content part
            ContentDefinitionManager.AlterPartDefinition(
                "BandiAvvisiPart"
                , b => b
                    .Attachable()
                    .WithField("Destinatari", cfg => cfg.OfType("TaxonomyField").WithDisplayName("Destinatari").WithSetting("TaxonomyFieldSettings.Taxonomy", "Destinatari"))
                    .WithField("AreeTematiche", cfg => cfg.OfType("TaxonomyField").WithDisplayName("Aree tematiche").WithSetting("TaxonomyFieldSettings.Taxonomy", "Aree tematiche"))
                    .WithField("FondiProgrammi", cfg => cfg.OfType("TaxonomyField").WithDisplayName("Fondi e programmi").WithSetting("TaxonomyFieldSettings.Taxonomy", "Fondi e programmi"))
                    .WithField("DataApertura", cfg => cfg.OfType("DateTimeField").WithDisplayName("Data apertura"))
                    .WithField("DataScadenza", cfg => cfg.OfType("DateTimeField").WithDisplayName("Data scadenza"))
                    .WithField("Allegati", cfg => cfg.OfType("MediaLibraryPickerField").WithDisplayName("Allegati")
                        .WithSetting("MediaLibraryPickerFieldSettings.Required", "True").WithSetting("MediaLibraryPickerFieldSettings.Multiple", "False")));
            // creo il content type: 
            ContentDefinitionManager.AlterTypeDefinition(
                "BandiAvvisi"
                , cfg =>
                    cfg
                        .WithPart("BandiAvvisiPart")
                        .WithPart("IdentityPart")
                        .WithPart("TitlePart")
                        .WithPart("CommonPart")
                        .WithPart("AutoroutePart")
                        .WithPart("BodyPart")
                        .Creatable()
                        .Listable()
                        .Draftable()
                        .Securable()
            );

            return 1;
        }

        public Recipe LoadRecipe(string filepath)
        {
            return _recipeParser.ParseRecipe(_webSiteFolder.ReadFile(filepath));
        }

        public string Execute(Recipe recipe)
        {
            var executionId = _recipeManager.Execute(recipe);

            // Only need to update the shell if work was actually done.
            if (executionId != null)
                UpdateShell();

            return executionId;
        }

        public void UpdateShell()
        {
            var descriptor = _shellDescriptorManager.GetShellDescriptor();
            _shellDescriptorManager.UpdateShellDescriptor(descriptor.SerialNumber, descriptor.Features, descriptor.Parameters);
        }
    }
}

**Comment by sebastienros** [comment] 2018-11-08 20:05
I don't think the issue is that the recipe has not run yet, but that the database transaction hasn't been committed. Try to look for a sample that calls `session.Flush()` and do the same think after `Execute`.

**Comment by luciofassio** [comment] 2018-11-09 13:46
I searched for session.Flush() and found (only in the unit test projects):

            _databaseFilePath = Path.GetTempFileName();
            _sessionFactory = DataUtility.CreateSessionFactory(_databaseFilePath, DatabaseTypes.ToArray());
            _session = _sessionFactory.OpenSession();
            _transaction = _session.BeginTransaction(IsolationLevel.ReadCommitted);
           ......
           _sessionFlush()

but i don't have any explicit session nor transaction open when i call `Execute`, have I to do that?

Thank you in advance.

**Comment by sebastienros** [comment] 2018-11-15 20:06
Resolve `ITransactionManager`, from which you can get a session: `_transactionManager.GetSession()` then call `Flush()` on the session.

**Comment by BenedekFarkas** [comment] 2019-08-13 13:42
@luciofassio please reopen or follow-up on [Gitter](https://gitter.im/OrchardCMS/Orchard) if this question is still relevant.

**Closed as completed by BenedekFarkas** 2019-08-13 13:42 UTC
Labels: question
