### ISSUE TITLE
Recipe import should support updating a draft content item where there is no published version

### ISSUE THREAD

**Issue by jimasp** [OrchardCMS/Orchard#5330] opened 2015-05-28 10:57 UTC
**Problem**

When you import a content item with a status of draft in the recipe file, it will not find and update the existing draft item via the identity part identifier in the recipe, unless that content item also has a published version. 

It will instead create a new draft, which is not intended.

**Cause**

The IdentifierResolverSelector.ResolveIdentity() method only queries published items (because the default VersionOption for queries is VersionOptions.Published):

    return _contentManager.Query<IdentityPart, IdentityPartRecord>()...

Thus, if there is no published version of the content item, the content item will not be found via its identity part identifier.

Consequently, a new draft content item will be created every time you run the import for a draft item when there is no published version.

**Proposed solution**

Change the IdentifierResolverSelector.ResolveIdentity() to get the latest version (i.e. include drafts):

    return _contentManager.Query<IdentityPart, IdentityPartRecord>(VersionOptions.Latest)...

**Additional notes**

1. The actual version of the content item used (regardless of the version matched) is controlled by the ImportContentSession.Get() method, further up the stack:

    ContentItem existingItem  = _contentManager.ResolveIdentity(contentIdentity);
    
    //ensure we have the correct version
    if (existingItem != null) {
        existingItem = _contentManager.Get(existingItem.Id, versionOptions);
    }

2. There are other ResolverSelector classes, e.g. AliasResolverSelector. These also only Query published versions.

**Comment by sebastienros** [comment] 2015-05-28 20:02
Duplicate of #4097

Please provide a PR with your recommended fix, this is an important issue.

**Closed by sebastienros** 2015-05-28 20:02 UTC

**Comment by jimasp** [comment] 2015-06-01 15:47
PR as requested: https://github.com/OrchardCMS/Orchard/pull/5341
