### ISSUE TITLE
bootstrap Layout for widget orchard core

### ISSUE THREAD

**Issue by vibhan1991** [OrchardCMS/Orchard#8406] opened 2020-08-13 12:39 UTC
How to add layout options like 20 %  in widget container i am new in orchard core can any one help me to resolve this issue.
![Untitled](https://user-images.githubusercontent.com/69633394/90135232-fcd37600-dd8f-11ea-8895-0fab64a4244a.png)

You can see in this image with marked in which i want 20 % as option .

**Comment by sebastienros** [comment] 2020-08-13 17:07
Wrong repository, can you file it in OrchardCore?

But duplicate of https://github.com/OrchardCMS/OrchardCore/issues/6453

**Closed as completed by sebastienros** 2020-08-13 17:07 UTC
