### ISSUE TITLE
Added Fields not shown in custom Content Definition and can't be deleted

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/Orchard#6310] opened 2016-01-28 09:58 UTC
I've created a new Content Definition named "Employee".
Adding a Field with Type "Media Library Picker Field" named "Image" does'nt work because Fields not displaying after saving (so i can't delete them).
Now i deleted the whole "Employee"-Item and created it again, but when I try to add the Field "Image" it says that this Field already exists.

**Comment by sfmskywalker** [comment] 2016-01-28 11:09
Which branch is this?

**Comment by Flarescape** [comment] 2016-01-28 11:30
Oh sry!
v1.9.2.0

The strange thing is, I tried it in my test page and it works.
The only difference between this sites is, that in the one with the described issue, the search module is enabled.
Also the DB entries are equal. (The fields are in the DB)

**Comment by sebastienros** [comment] 2016-01-28 20:59
Can you provide some simple repro steps?

**Comment by Flarescape** [comment] 2016-01-29 08:10
I finally reproduced it in my test page.
I don't know exactly which of these steps are relevant for the issue, but this is what i did:
1.) Create some pages in a clean and new orchard 1.9.2
2.) Go to Modules and enable Search, Lucene, Admin Content Search
3.) Go to Settings > Indexes and create a new "Search Index"
4.) Settings > Search add the new Index and save it 
5.) Content Definition > Page and give the "Page" definition the search index and save
6.) Settings > Indexes and click update on the index
7.) Settings > Search click the save button to show the available fields in the index and check "title" than save
8.) Settings >  Admin Search and do the same thing as in 7.
9.) Content Definition > Create New Type and call it "Employee"
10.) After creating the "Employee" definition and before creating any fields hit save
11.) Click "Add Field" in the "Employee" definition and name it "Image"
12.) Now i made a mistake and enter "Employee_Image" in the "Technical Name" field 
13.) Type of the field should be "Media Library Picker"
14.) Click save 
15.) A error is shown that the technical name can't contain a "_" so change it to "EmployeeImage"
16.) Now when saving the field again it won't show but it is in the DB
17.) Since then I can't add other fields to the "Employee" because they don't appear in the fields section of the "Employee" definition

Now you can delete the definition and create it again, but it won't work to add the same fields cause they are already in the DB.

I hope it's only because I did something wrong and that it could be fixed easily. :)

**Comment by Flarescape** [comment] 2016-01-29 08:29
PS:
My idea was, that maybe the problem is the checkbox named "Include in the Index" that shows on every field after configuring the search ?! (eventually problems with the view or something like this?)

**Comment by sfmskywalker** [comment] 2016-01-29 09:31
Sounds like the issue is with the technical field and validation.

**Comment by Flarescape** [comment] 2016-01-29 10:12
![image](https://cloud.githubusercontent.com/assets/1375119/12672754/ca946f4c-c678-11e5-80f5-77579c7fb788.png)

This is how it looks like in the DB.
The technical name is correct.
This is german cause i'm from austria so MitarbeiterBild means EmployeeImage.

**Comment by Flarescape** [comment] 2016-02-01 09:19
**Update:**
I've tested a view things and I ended with the following thing:
If I create a "Employee" definition in a Orchard 1.8.1.
Then export this definition and import it into the 1.9.2, where the fields at the "Employee" definition not shown.
The definition gets created with the normal fields of the imported definition **AND** all fields that are not shown are now also displaying within the "Employee".

**Comment by Flarescape** [comment] 2016-02-15 08:16
**FIX:**
The problem is a single db entry in the **Settings_ContentTypePartDefinitionRecord** table.
For example the Employee definition has no relation between its Type and Part definition.
This entry is missing:
![image](https://cloud.githubusercontent.com/assets/1375119/13042908/8bedcdac-d3c4-11e5-869a-4afbf8bd79cf.png)

If you insert the missing entry with the correct id's everything works.

**Comment by CodeCharm** [comment] 2016-08-03 04:11
I think I'm seeing this issue, too, only I don't have DB access to patch it.

One thing I notice (not sure if this is helpful because I'm not a regular Orchard developer) is that the new fields in the new content type do show if I follow a link from the Audit Trail report (a backwards way in), but not if I just try to edit the custom Content Type.

In other words, this link does not show the custom fields:
https://example.net/Admin/ContentTypes/Edit/ContactRequest (the page title is "Edit Content Type - Contact Request")

... while this link _does_ show the custom fields I added for the same custom content type:
https://example.net/Admin/ContentTypes/EditPart/ContactRequest (the page title is "Edit Part")

However, I could not find any more direct way to show the "Edit Part" page. Even so, I would expect that the Fields would show up on the "Edit Content Type" page.

running Orchard v.1.9.3.0 on Azure

**Comment by CIO-DOTNET** [comment] 2017-11-15 10:14
This issue is still present on Orchard v1.10.2. Steps followed are similar:

1) Go to Content Definition
2) Select "User"
3) Select "Add Field"
4) Get validation error when including underscore "_" in field name.
5) Correct error and save
6) Field doesnt appear in field list
7) Any subsequent new field additions dont appear either

**FIX:**
As described above, find the **<db_prefix>_Settings_ContentTypePartDefinitionRecord** table, and add manually the record, where **ContentPartDefinition_id** corresponds to the column of the same name in **<db_prefix>_Settings_ContentPartFieldDefinitionRecord** and **ContentTypeDefinitionRecord_Id** corresponds to the *Id* column ** in **<db_prefix>_Settings_ContentPartFieldDefinitionRecord**

**Comment by sebastienros** [comment] 2017-11-16 20:05
Does it all repro when we do not go through steps 4 and 5 ?

**Comment by CIO-DOTNET** [comment] 2017-11-30 15:51
Hi Sebastien,
I have created two new Content Definitions to test this out.

For the first content definition, I tried adding a field without having any invalid characters, and the field was saved and displayed as expected in the Field List (omitting steps 4 and 5)

For the second content definition, I followed the same steps described above and this error has occurred again.

**Comment by BenedekFarkas** [comment] 2019-08-27 20:28
Fixed in #f46be479a3d3a68cd2bcc5e9704e3efbfdafa6f6.

**Closed by BenedekFarkas** 2019-08-27 20:28 UTC
