### ISSUE TITLE
TinyMCE settings module - custom stylesheet

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#5160] opened 2015-04-15 14:32 UTC
Feature Request: It would be great if we could specify the style sheet for rendering the content within the TinyMCE editor.  I know the config can do this, we just need to have the config render out based on settings set in the database.  The CKEditor module supports this, however the new Layouts module requires TinyMCE - so implementing this functionality in TinyMCE would be ideal.

**Comment by sebastienros** [comment] 2015-04-16 19:29
This could be done as a site setting for TinyMCE so that it uses this when editing. It can't be taken automatically from the theme, even more because it's an Admin theme concern.

@bleroy is mentioning that OneStop has something like this. He'll see if they can share.

**Comment by dcinzona** [comment] 2015-04-16 19:30
Awesome.  And yes, agree with this being a site setting and *not* automatically grabbing it from the active front-end theme).

**Comment by Skrypt** [comment] 2015-04-18 22:32
You could also only edit the TinyMCE module for yourself and edit the \Orchard\src\Orchard.Web\Modules\TinyMce\Scripts\orchard-tinymce.js file and add
the configuration missing for it to work found there : 
http://www.tinymce.com/wiki.php/Configuration:content_css

Then you could manage front-end needed styles in that CSS. Remember though to never override Orchard specific admin classes. You could, for that, use LESS or SASS and include all these classes to be nested inside TinyMCE main content item class.

```
.mce-tinymce{
      #Body_Text{
          .youreditorclass1{
               background-color:#FFF;
          }

          .youreditorclass2{
               background-color:#000;
          }
      }
}
```

Going with this approach maybe you could copy/paste all your current front-end css classes in there with using LESS.

On the frontend LESS file "implies you use a css class to the body tag in your HTML named front-end-styles"
```
.frontend-styles{
    allyourclassesinhere{}
}
```

On the TinyMCE LESS file
```
.mce-tinymce{
      #Body_Text{
          .frontend-styles;
      }
}
```

P.S. need to test that one

**Comment by dcinzona** [comment] 2015-05-08 19:06
TinyMce also has a setting where you can load a CSS stylesheet into the iframe.  That is the option we are taking because all you need to do in that case is provide a relative path to your active theme's stylesheet.
This could be a one liner in settings.  Or (much more complicated), maybe a list of stylesheets if you have multi-tenancy or multiple themes and you want to be able to select which style sheet to use for the editor.  Then, when the editor is visible, a drop down menu is available where the user can pick which stylesheet to use.   Selecting a new stylesheet would reload the editor.

**Comment by sebastienros** [comment] 2015-08-27 19:34
Duplicate of #2657

**Closed by sebastienros** 2015-08-27 19:34 UTC
Labels: enhancement
