### ISSUE TITLE
Shape Tracing Module doesn't work

### ISSUE THREAD

**Issue by AlexanderStasyuk** [OrchardCMS/Orchard#5661] opened 2015-08-19 14:00 UTC
When turning shape tracing module on errors come up.  This happens on a fresh install.

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.
OrchardCMS\Orchard-dev\Orchard-dev\src\Orchard\DisplayManagement\Implementation\DefaultShapeFactory.cs    Line: 90

**Comment by Piedone** [comment] 2015-08-20 18:27
Duplicate of #5647.

**Closed by Piedone** 2015-08-20 18:27 UTC
