### ISSUE TITLE
File System Output Cache has error

### ISSUE THREAD

**Issue by zhhbo** [OrchardCMS/Orchard#7660] opened 2017-04-12 05:25 UTC
I meet this:
 An unexpected error occurred while reading a cache entry [http://www.orchardcn.org/Users/Account/LogOn?ReturnUrl=%2FUserCenter%2FContent%2FList%2FArticle] System.ArgumentException: Invalid path 在 Orchard.Validation.PathValidation.ValidatePath(String basePath, String mappedPath) 位置 D:\Orchard1\Orchard\src\Orchard\Validation\PathValidation.cs:行号 32 在 Orchard.FileSystems.AppData.AppDataFolder.CombineToPhysicalPath(String[] paths) 位置 D:\Orchard1\Orchard\src\Orchard\FileSystems\AppData\AppDataFolder.cs:行号 95 在 Orchard.FileSystems.AppData.AppDataFolder.FileExists(String path) 位置 D:\Orchard1\Orchard\src\Orchard\FileSystems\AppData\AppDataFolder.cs:行号 158 在 Orchard.OutputCache.Services.FileSystemOutputCacheStorageProvider.<>c__DisplayClass12_0.<GetCacheItem>b__0() 在 Orchard.OutputCache.Services.FileSystemOutputCacheStorageProvider.Retry[T](Func`1 action) 在 Orchard.OutputCache.Services.FileSystemOutputCacheStorageProvider.GetCacheItem(String key) 

I think the error was caused by FileSystemOutputCacheStorageProvider.GetCacheItemFilename(string key) method,
If there  a question mark in the URL, you will not be able to create the cache file, which will cause the exception

**Comment by sebastienros** [comment] 2017-04-13 19:24
What version are you using?
I think we have already fixed this issue.

**Comment by zhhbo** [comment] 2017-04-13 22:11
v1.10.2
not fixed
fileoutputprovide line 117

**Comment by gvkries** [comment] 2017-05-09 12:00
I think this is a duplicate of bug #6115 or it is at least the same reason.

**Comment by sebastienros** [comment] 2017-05-09 15:36
It doesn't look like a duplicate of #6115. One is about long filenames and the other about invalid chars.
I don't remember why I closed my own PR, there was probably some issues with what I had done.

I will try to start again from this PR and see what could be the issue. (locking, size growth/limits).

**Comment by gvkries** [comment] 2017-05-09 15:56
You are right, the file names are based on URL encoded cache keys, there can be any invalid chars. So actually not the same issue, but same source ;-)

Anyway, thanks for looking at the PR.

**Comment by sebastienros** [comment] 2018-09-20 19:36
fixed by https://github.com/OrchardCMS/Orchard/pull/7913

**Closed by sebastienros** 2018-09-20 19:36 UTC
