### ISSUE TITLE
Users last login time is not correct

### ISSUE THREAD

**Issue by roballred** [OrchardCMS/Orchard#7071] opened 2016-08-05 15:28 UTC
This is in version 1.10.1.0, so if it got fixed please disregard. I did a search and didn't see anything about it. I have attached a screen cap of the problem but basically it say my last login time is 2016 years ago. I must be really old.
![issue](https://cloud.githubusercontent.com/assets/549504/17441581/92438daa-5ae6-11e6-87dd-eb831e9e9a3f.JPG)

**Comment by sebastienros** [comment] 2016-08-05 16:44
Weird, because the existing issue and PR which fixed it was submitted 6 months ago. We closed the same bug as a duplicate yesterday.

**Comment by jchenga** [comment] 2016-08-10 16:51
See comment by @BenedekFarkas in #6664. The problem is still in 1.10.x version, because the fix is in the dev branch but not in 1.10.x.

**Closed** 2016-10-22 10:17 UTC
