### ISSUE TITLE
If a deprecated module is activated by error, it is impossible to disactivate it

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6598] opened 2016-03-17 16:35 UTC
I add this bad sequence with jQuery module...

... //hmmm...I feel like I've done this before...

**Comment by sebastienros** [comment] 2016-03-17 19:38
"It is impossible to deactivate it" How does it look like? Doesn't the feature appear in the features list still?

**Comment by CSurieux** [comment] 2016-03-17 19:52
Try it, clic on enable.


Envoyé via Outlook Mobile






On Thu, Mar 17, 2016 at 12:38 PM -0700, "Sébastien Ros" <notifications@github.com> wrote:





"It is impossible to deactivate it" How does it look like? Doesn't the feature appear in the features list still?

---

**Comment by sebastienros** [comment] 2016-03-17 20:59
Anyone could try, it could be even more easy for us to understand what the issue is if you already know what is preventing you from disabling it. And maybe just with this we could conclude there is an issue and assign it to the correct milestone, or get an idea of the effort to fix it, or simply state it's by design.

**Comment by CSurieux** [comment] 2016-03-17 21:14
Well, the code prevent generating the disable link.

**Comment by sebastienros** [comment] 2016-03-17 21:18
Thanks, exactly the information I wanted to know.

**Closed** 2016-05-10 06:10 UTC
