### ISSUE TITLE
Tinymce should allow changing the font family and font size

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6730] opened 2016-04-07 21:20 UTC
Without changing in js code its start options.
NB: In wordpress there is a nice setting dedicated to tinyMCE
see http://www.theaaronloy.com/enable-font-size-menu-in-tinymce-wordpress-easy/

**Comment by sebastienros** [comment] 2016-04-11 23:14
Agreed, duplicate of https://github.com/OrchardCMS/Orchard/issues/2657

**Closed by sebastienros** 2016-04-11 23:14 UTC
