### ISSUE TITLE
Feature Request: Allow developers to specify arbitrary locations to load Modules and Themes from

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/Orchard#5241] opened 2015-05-05 12:23 UTC
It'd be good to be able to bootstrap in additional locations that Orchard should search for extensions (ie Modules and Themes).

One such use case would be to allow for deployments of Modules or Themes separately from the deployment of the Orchard codebase by placing these custom extensions into a folder different to `~/Modules` or `~/Themes`.

**Comment by pszmyd** [comment] 2015-05-05 12:35
That's a very good idea. I remember this request surfacing from time to time.

**Comment by paynecrl97** [comment] 2015-05-05 12:41
I made a quick prototype of this feature a few weeks ago, but I'm struggling to find the branch (I may have accidentally deleted it).

It involved registering the additional extension locations from within the `Host.config` file.

I'll see if I can dig up the changes I made so we can open them up for discussion.

**Comment by dcinzona** [comment] 2015-05-05 13:43
+1
This would be great when trying to organize default Orchard modules vs custom internal modules.

**Comment by paynecrl97** [comment] 2015-05-05 14:41
@dcinzona: That is exactly the use case we have for this feature too.

Currently we just dump all of our custom modules into the `~/Modules` folder, which means that things can get quite messy.

**Comment by dcinzona** [comment] 2015-05-05 14:42
@paynecrl97  Yup, us as well.  We just organized the Orchard solution so that we have them separated in the solution itself, but the file system still contains everything in that single directory.

**Comment by paynecrl97** [comment] 2015-05-05 15:39
I re-created my prototype to show one way that this would be possible: https://github.com/OrchardCMS/Orchard/compare/OrchardCMS:1.x...paynecrl97:5241/extension_locations?expand=1

This allows you to register custom locations in your `Host.config` file eg:

            <component instance-scope="single-instance" type="Orchard.Environment.Extensions.Folders.ModuleFolder, Orchard.Framework" service="Orchard.Environment.Extensions.Folders.IExtensionFolders, Orchard.Framework">
              <parameters>
                <parameter name="path" value="~/CustomModules"/>
              </parameters>
            </component>

I've done some very light testing, and I think this will only work for modules (themes can be achieved in a very similar fashion).

I know far too little to be able to say if this will work for all edge cases, so I'm seeking feedback from someone who knows more on this area.

Additionally- I'd welcome any feedback on the methodology used.

**Comment by Xceno** [comment] 2015-05-07 15:14
+1
This would be really helpful!

**Comment by Piedone** [comment] 2015-05-07 15:16
Duplicate of #5019.

**Closed by Piedone** 2015-05-07 15:16 UTC
