### ISSUE TITLE
Dynamic module compilation and C# 6 features

### ISSUE THREAD

**Issue by Xceno** [OrchardCMS/Orchard#5408] opened 2015-06-22 10:50 UTC
Hi all,

this ain't a high priority thing but I thought I mention it, so it's on the radar.

I wanted to try out some of the new C# 6 features which isn't a problem if you compile your module and then run Orchard.

However, if Orchard is running and the dynamic compilation kicks in, an exception get's thrown when it hits code that utilizes those features (like the new null conditional operator)

``` C#
mailListPart.Record.QueryPartRecord = memberSourceQueryPart?.Record;
```

Here's the exception:

```
System.Web.HttpCompileException (0x80004005): c:\Work\Stash\Orchard\src\Orchard.Web\Modules\MyModule\Handlers\MailListPartHandler.cs(85): error CS1525: Invalid expression '.'.
   at System.Web.Compilation.BuildManager.PostProcessFoundBuildResult(BuildResult result, Boolean keyFromVPP, VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetBuildResultFromCacheInternal(String cacheKey, Boolean keyFromVPP, VirtualPath virtualPath, Int64 hashCode, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultFromCacheInternal(VirtualPath virtualPath, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResult(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetCompiledAssembly(String virtualPath)
   at Orchard.Environment.DefaultBuildManager.GetCompiledAssembly(String virtualPath) in C:\Work\Stash\Orchard\src\Orchard\Environment\IBuildManager.cs:Line 53.
```

It gets thrown here (_Orchard\Environment\IBuildManager.cs:Line 53_).

``` C#
public Assembly GetCompiledAssembly(string virtualPath) {
    try {
        return BuildManager.GetCompiledAssembly(virtualPath);
    }
    catch (Exception ex) {
        if (ex.IsFatal()) throw;

        Logger.Warning(ex, "Error when compiling assembly under {0}.", virtualPath);
            return null;
    }
}
```

I spent some time searching the web for more info on why exactly it fails, but I couldn't find anything helpful so far.

**Comment by sfmskywalker** [comment] 2015-06-22 10:53
I just ran into this myself as well.

**Comment by armanforghani** [comment] 2015-09-06 03:10
I have the same problem. Impatiently waiting to upgrade.

**Comment by Xceno** [comment] 2016-01-18 08:53
So we have this commit now from @DanielStolt (c59b761c3a1542e4edc0135724cb536e816b3132) which enables c# 6 syntax support in Razor views.
I cannot test the dev branch right now, but does this commit also fix this issue or is it a razor-only-fix?

**Comment by DanielStolt** [comment] 2016-01-18 10:41
@Xceno I have been wondering that myself. I'm not familiar enough with how the dynamic compilation in Orchard works, I know it uses the Build Manager in `System.Web` to compile the projects, but whether this is influenced by the `CodeDom` providers I have now added to `Web.config` remains to be seen I guess. Please do report back if and whenever you get a chance to test it!

**Comment by sebastienros** [comment] 2016-01-19 23:50
This must be something like this `_codeCompilerType.CompilerParameters.CompilerOptions += string.Format("/langversion:6 /define:ORCHARD_{0}_{1}", orchardVersion.Major, orchardVersion.Minor);` in `CSharpExtensionBuildProviderShim` but I don't know what is the requirement on the server for it to work.

Also, we need to look at how we can target a specific framework (like 4.5.2 currently).

**Comment by BenedekFarkas** [comment] 2016-08-03 22:19
I just tested the changes by @DanielStolt from 7 month ago about adding C# 6 support for Razor views (with the change immediately after that to set every project to 4.5.2: dec68d454c90536d2ca335cf46f35346fb2ca03a) and it works great!
@sebastienros later reverted the change adding the C# 6 support (3630473e693598b0323901fec91cab5020ee98b9), so it didn't make it into 1.10.1 - any news on this?

Unfortunately, in my experience, `Dynamic Compilation` in `1.10.1` is almost useless.

Btw I tried Sébastien's suggestion to add an additional parameter to the `CompilerOptions` and it yields a lot of debug errors (same as before the change), e.g. when I modify `LayoutPartDriver`:
`
2016-08-04 00:13:37,419 [78] Orchard.Environment.DefaultBuildManager - Default - WARN Error when compiling assembly under ~/Modules/Orchard.DynamicForms/Orchard.DynamicForms.csproj.
System.Configuration.ConfigurationErrorsException: Could not load file or assembly 'Orchard.Layouts' or one of its dependencies. The system cannot find the file specified. (E:\DEV\Orchard\Orchard CMS\src\Orchard.Web\modules\orchard.dynamicforms\web.config line 35) ---> System.IO.FileNotFoundException: Could not load file or assembly 'Orchard.Layouts' or one of its dependencies. The system cannot find the file specified.
`

One thing I would add though - and this is something that we should follow as a convention when decided - is whether we should use string interpolation in T-strings. From a translators point of view, this could be a source for mistakes (although Crowdin detects special characters like that and handles special parts of the string nicely). What is also notable is that `Vandelay.TranslationManager` (Bertrand's module that can extract T-strings from source files) does not handle such strings (due to the addition of the `$` character), but it's probably not a big deal to fix that.

**Comment by BenedekFarkas** [comment] 2017-01-10 00:27
Here's a PR to fix Dynamic Compilation to support C# 6: https://github.com/OrchardCMS/Orchard/pull/7508
There are still debug log entries for some of the modules (Dashboards, Layouts) even when they aren't modified, but there's no runtime issue with that and it was reproducible before this change well - I'll try to fix those as well anyway.

**Comment by sebastienros** [comment] 2017-01-10 00:33
I reverted it because it broke things. Have you tried to run the specflow tests, I would start with it.

**Comment by sebastienros** [comment] 2017-01-12 20:21
Also when you say "dynamic compilation is almost useless in 1.10.1" do you mean it doesn't work anymore (that would surprise me). And do you mean that your PR is breaking the feature. I assume that's the reason I reverted Daniel's change.
I would not take it in 1.10.2 as it's too risky. It's a good candidate for 1.11.

**Comment by BenedekFarkas** [comment] 2017-01-12 21:34
Dynamic Compilation does not work at all in 1.10.1 if it has to compile any code that contains C# 6 language features, the PR I sent in fixes that (but I'll do some further testing, because some of the SpecFlow tests are failing / throwing a warning). Daniel's changes are about Razor compilation - I haven't checked yet whether those changes cover Dynamic Compilation or not.

**Comment by DanielStolt** [comment] 2017-01-13 14:08
The change I made did not cover dynamic module compilation (of code), it only covered Razor views which are dynamically compiled either way. As far as I recall though, with my change there was no problem using C# 6 syntax in Razor views in either case, whether the module itself was pre-compiled or dynamically compiled.

**Comment by teamaton** [comment] 2017-09-15 20:55
@BenedekFarkas Thank you so much for putting your time and effort into fixing the compilation for newer C# versions! We've finally come around to implement your changes and (after some gitignore problems) can finally get back to saving and hitting F5!

**Comment by sebastienros** [comment] 2017-09-21 19:26
@BenedekFarkas is everything fixed now?

**Comment by BenedekFarkas** [comment] 2017-11-01 14:12
Hi @teamaton thanks for the feedback - so you applied these changes without any additional work (besides the gitignore) and it worked?
@sebastienros I'll do some further testing myself, I'll try to get around to finish this soon!

**Comment by teamaton** [comment] 2017-11-02 10:25
Yes, Benedek's diff did it for us - we haven't had any problems with that solution :-)

**Comment by sebastienros** [comment] 2017-11-02 19:05
Good to know

**Comment by BenedekFarkas** [comment] 2017-11-07 00:23
Here's the new PR: #7891 
Also includes Razor IntelliSense and it's targeting 1.10.x. If and when it's merged, 1.10.x should be merged into dev and I'll create a separate PR to update that as well (since there are a few more modules on that branch).

Btw these changes also work with C# 7 as well (if the target language version is 7 instead of 6), but VS 2015 doesn't seem to support that at all for regular compilation.

**Comment by BenedekFarkas** [comment] 2017-11-07 22:27
Updated PR with codegen changes: `packages.config` added with all the necessary packages (+ codegen commands update), package references and root web.config updated.

**Comment by BenedekFarkas** [comment] 2017-11-09 17:22
@sebastienros are we OK to merge this? Maybe with someone else testing it as well.

**Comment by sebastienros** [comment] 2017-11-09 18:52
We merge on Thursdays

**Comment by BenedekFarkas** [comment] 2017-11-09 19:08
I'll bring popcorn! :D

**Closed** 2017-11-10 14:14 UTC
