### ISSUE TITLE
TinyMCE editor strips out inline style code

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#5518] opened 2015-07-16 14:15 UTC
We were playing around with the layouts module, which requires TinyMCE, and noticed that the editor (in any situation) will strip out inline `<style></style>` tags.  This became problematic as we override some stiles in certain instances on the site.
As such, we can't use TinyMCE and Layouts until this is fixed by the editor.  I've looked at the configs and it looks like it's set to allow all tags, but for some reason, it still gets stripped.

We are using CKEditor instead of TinyMCE.  I wish the layouts module was editor agnostic.
See issue https://github.com/OrchardCMS/Orchard/issues/5112

**Comment by donaldboulton** [comment] 2015-07-24 17:58
It does not require Tiny MCE. install CKEditor and enable it. No more stripping of inline css, or use ace.

**Comment by sebastienros** [comment] 2015-08-27 19:30
Duplicate of #2657

**Closed by sebastienros** 2015-08-27 19:30 UTC
