### ISSUE TITLE
Invalid part names are allowed

### ISSUE THREAD

**Issue by MatteoPiovanelli** [OrchardCMS/Orchard#7887] opened 2017-10-26 14:07 UTC
I was playing around with content types, and I happened upon this issue:

1. Create a new part from back office and call it: `zxc"`
    The quotes " are part of the name you should input.
2. Go in a content type and add the newly created part.
3. Attempting to remove the part fails.

If you called the part `qew""`, with two quotes, you would have been able to remove it form the content type.

I guess there is some validation that is missing?

**Comment by sebastienros** [comment] 2017-10-26 19:10
Sure

**Comment by Xceno** [comment] 2017-10-27 08:58
@MatteoPiovanelli-Laser I think this PR is related: https://github.com/OrchardCMS/Orchard/pull/7771
Here's the issue: https://github.com/OrchardCMS/Orchard/issues/7770

**Comment by MatteoPiovanelli** [comment] 2017-10-27 10:10
I guess. I don't know what the `ToSafeName()` method does, in detail.

**Comment by sebastienros** [comment] 2017-11-02 19:09
@Xceno that's exactly it and I stand by by comment, we should add a validation message and not just change the value the user entered.

**Comment by sebastienros** [comment] 2017-11-02 19:10
Duplicate of #7770

**Closed as completed by sebastienros** 2017-11-02 19:10 UTC

**Comment by Xceno** [comment] 2017-11-03 07:43
@sebastienros Okay, I'll fix this as soon as I get back into Orchard land. Sorry for the delay!
