### ISSUE TITLE
Admin missing menu.aliases-admin.css

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6651] opened 2016-03-25 14:04 UTC
Admin Modules page says its missing menu.aliases-admin.css.
Searched the unzipped 1.10 folder and found nothing asking for it ??????

**Comment by BenedekFarkas** [comment] 2016-03-26 09:48
Duplicate of #6430 (fixed with a PR on `dev`). We could apply this to 1.10.x as well - @sebastienros?

**Closed** 2016-03-31 19:32 UTC
