### ISSUE TITLE
Missing css files when editing a workflow

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#5323] opened 2015-05-25 20:12 UTC
When editing a workflow, with the browser tools I can see some errors about missing css files. I can fix it by adding empty files in the Styles folder of the related modules

    workflows-activity-logging.css (in Orchard.Workflows/Styles)
    workflows-activity-add-model-error.css (in Orchard.DynamicForms/Styles)
    workflows-activity-dynamic-form-submitted.css (in Orchard.DynamicForms/Styles)
    workflows-activity-dynamic-form-validating.css (in Orchard.DynamicForms/Styles)

Best

**Comment by Piedone** [comment] 2015-05-26 18:29
Duplicate of #4358.

**Closed by Piedone** 2015-05-26 18:29 UTC
