### ISSUE TITLE
Strange recipe execution error

### ISSUE THREAD

**Issue by VladimirPan** [OrchardCMS/Orchard#5494] opened 2015-07-09 16:31 UTC
Hello,

I have a really strange issue when trying to execute recipes.
Using the command: orchard.exe recipes execute Orchard.Setup recipe3

The recipe3 is pretty much simple (I cannot attach it here). But this recipe just adds a new layer and widget to my web site.

For some of my computers it works, but for some other doesn't.

I see an error in execution console:
orchard> recipes execute Orchard.Setup recipe3
Recipe scheduled for execution successfully.
Error:
  Exception has been thrown by the target of an invocation.
  Object '/555e7d0b_f4fc_45de_b087_e213094146f9/7lykaihpanw87x8wwskupwaj_12.rem' has been disconnected or does not exist
 at the server.

... and error in the error log:
{ERROR} 2015-07-08 15:25:45,672 [1] NHibernate.Event.Default.AbstractFlushingEventListener - Could not synchronize database state with session
NHibernate.StaleStateException: Batch update returned unexpected row count from update; actual row count: 0; expected: 1
   at NHibernate.AdoNet.Expectations.VerifyOutcomeBatched(Int32 expectedRowCount, Int32 rowCount)
   at NHibernate.AdoNet.SqlClientBatchingBatcher.DoExecuteBatch(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatchWithTiming(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatch()
   at NHibernate.Engine.ActionQueue.ExecuteActions()
   at NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)

I don't think this is database related issue, because on other computer this database works.
Btw application pool was stopped when I run this recipe.

Could somebody can help me to understand what's going on here?

Thank you!

**Comment by sfmskywalker** [comment] 2015-07-09 16:41
Do you have any 2nd level cache enabled? What database server are you running?

**Comment by VladimirPan** [comment] 2015-07-09 16:43
No, I haven't any 2nd level cache.
I'm using MS SQL Server 2008 R2 64-bit Enterprise.
Thank you!

**Comment by sfmskywalker** [comment] 2015-07-09 16:44
Which Orchard version?

**Comment by VladimirPan** [comment] 2015-07-09 16:45
Orchard 1.6

**Comment by sfmskywalker** [comment] 2015-07-09 16:46
Can you try on 1.9.1?

**Comment by dcinzona** [comment] 2015-07-09 16:47
I get that same exact error every day, once a day (around 6:30am). (once for each instance).  No 2nd level cache enabled for me either.  Running 1.9.1
See here: https://github.com/OrchardCMS/Orchard/issues/5480

**Comment by VladimirPan** [comment] 2015-07-09 16:47
Unfortunately I cannot my application won't work with newer version and I don't have time for migration.

**Comment by sfmskywalker** [comment] 2015-07-09 16:49
Duplicate of #5480

**Closed by sfmskywalker** 2015-07-09 16:49 UTC

**Comment by VladimirPan** [comment] 2015-07-09 16:50
The major problem for me is - I have this problem in production, but don't have it in development.
Using the same application code and recipes and same copy of database. The only difference is - server where I run these recipes.

**Comment by dcinzona** [comment] 2015-07-09 16:51
I am experiencing the same thing (no errors in QA, but errors in Production).  Production gets a lot more traffic than QA, obviously.  Not sure if that is related.  The environments are identical, otherwise.
