### ISSUE TITLE
Dependencies of modules, shouldn't be checked on every start of a tenant?

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard#5502] opened 2015-07-12 12:22 UTC
Currently dependencies of a module on other modules are only checked when you enable the module.
However, when you update the code of a module adding a new dependency on other feature and this dependency is not enabled on your tenants problems start. Something like this is happening to me with Piedone.Combinator an its new dependency on Orchard.Caching feature. When I start the tenants it fails to run. 
Yes Ican disable the updated module through an sql and after that enable another time the module, it will also enable the dependencies.
If you have a number of tenants that use this module, this manual option is something you don't like for your production site.

I have tried to enable dependent module in a migrations, but tenant failure happens before migrations is run.
So, don't you think it would be a good idea that when a tenant is started it checks the dependencies of its enabled modules to enable the disabled features that are a new dependency?

**Comment by Piedone** [comment] 2015-07-12 14:51
Duplicate of #3132.

**Closed by Piedone** 2015-07-12 14:51 UTC
